// Built-in i18n — zero external dependencies
// All translations stored here, managed via React context in i18nContext.tsx

export const translations: Record<string, Record<string, Record<string, string>>> = {
  en: {
    about: {"title":"About QR Code Generator","subtitle":"Our mission is to make QR code generation simple, fast, and accessible","mission":"Our Mission","m1":"We believe that QR codes should be accessible to everyone. Our platform provides a free, fast, and secure way to generate professional QR codes without any barriers to entry.","m2":"Whether you're a small business owner, marketer, or developer, our tool makes it easy to create QR codes for any purpose.","values":"Our Values","v1Title":"User First","v1Desc":"We prioritize user experience and make our tools intuitive and easy to use.","v2Title":"Performance","v2Desc":"Lightning-fast generation and real-time preview for the best experience.","v3Title":"Privacy","v3Desc":"All processing happens in your browser. We never store your data.","v4Title":"Accessibility","v4Desc":"Free to use, no registration required, accessible from anywhere.","why":"Why Choose Us?","w1":"35+ QR code types supported","w2":"Advanced customization options","w3":"Multiple export formats","w4":"Real-time preview","w5":"100% free and no registration","w6":"Completely private - processing in browser"},
    faq_page: {"title":"Frequently Asked Questions","subtitle":"Find answers to common questions about QR Code Generator","q1":"Is QR Code Generator free to use?","a1":"Your first 3 QR code generations are completely free. After that, we charge a tiny one-time fee of ₦1,000 for lifetime unlimited access.","q2":"Do I need to create an account?","a2":"No, you do not need to create an account. Even when paying, you just enter your email for the receipt.","q3":"Is my data stored on your servers?","a3":"No, all QR code generation happens entirely in your browser. We do not store any of your data on our servers.","q4":"What QR code types are supported?","a4":"We support 35+ QR code types including URLs, emails, phone numbers, WiFi networks, vCards, and much more.","q5":"Can I customize the appearance of QR codes?","a5":"Yes, you can customize colors, size, error correction level, margin, and more. You can also add logos.","q6":"What formats can I download QR codes in?","a6":"You can download QR codes as PNG, JPEG, SVG, and PDF.","q7":"Can I use these QR codes commercially?","a7":"Yes, absolutely. You can use QR codes generated here for any purpose - personal, commercial, or otherwise.","q8":"How do I scan a QR code?","a8":"Most modern smartphones have built-in QR code scanning. For other devices, you can use our QR Scanner tool.","q9":"What is error correction level?","a9":"Error correction level determines how much of the QR code can be damaged while still being scannable.","q10":"Can I edit a QR code after generating it?","a10":"You can regenerate a QR code with different settings, but QR codes are static once created. To change the content, generate a new QR code."},
    pricing_page: {"title":"Simple, Transparent Pricing","subtitle":"Try it for free, then pay once for unlimited access.","free":"Free Trial","free_price":"₦0","free_sub":"First 3 QR codes are on us","f1":"Up to 3 QR code generations","f2":"35+ QR code types","f3":"PNG & JPEG downloads","f4":"Custom colors and styles","f5":"Logo upload support","start_free":"Start Free Trial","premium":"Unlimited Access","premium_price":"₦1,000","premium_sub":"One-time payment, lifetime access","p1":"Unlimited QR code generations","p2":"All 35+ QR code types","p3":"High-res PNG, JPEG, SVG & PDF","p4":"Advanced customization","p5":"Premium logo support","p6":"No monthly subscriptions","get_unlimited":"Get Unlimited Access"},
    contact: {"title":"Contact Us","subtitle":"We would love to hear from you","get_in_touch":"Get in Touch","desc":"Have a question or suggestion? We are here to help. Send us a message and we will respond as soon as possible.","email":"Email","phone":"Phone","address":"Address","form_name":"Name","form_name_ph":"Your name","form_email":"Email","form_email_ph":"your@email.com","form_subject":"Subject","form_subject_ph":"How can we help?","form_message":"Message","form_message_ph":"Your message...","send":"Send Message","success":"Thank you for your message! We will get back to you soon."},

    nav: { scanner: 'Scanner', templates: 'Templates', blog: 'Blog', docs: 'Docs', about: 'About', contact: 'Contact', getStarted: 'Get Started' },
    blog: { title: 'Resources & Tutorials', subtitle: 'Master the art of QR codes for your business with our step-by-step guides.', read_article: 'Read Article', back: '← Back to Resources' },
    hero: { title: 'Professional QR Codes in Seconds', subtitle: 'Create beautiful, customizable QR codes with logo support. Your first 3 codes are 100% free — no registration required.', createBtn: 'Create QR Code', scanBtn: 'Scan QR Code', preview: 'QR Code Preview' },
    features: { title: 'Powerful Features', subtitle: 'Everything you need to create professional QR codes with advanced customization', f1Title: '35+ QR Types', f1Desc: 'Generate QR codes for URLs, emails, WiFi, vCard, payments, social media, and more', f2Title: 'Advanced Customization', f2Desc: 'Full control over colors, styles, logo placement, and frame designs', f3Title: 'Multiple Formats', f3Desc: 'Export as PNG, SVG, JPEG, PDF, or high-resolution for print', f4Title: 'Real-time Preview', f4Desc: 'See changes instantly as you customize your QR code', f5Title: 'Mobile Optimized', f5Desc: 'Works perfectly on all devices with responsive design', f6Title: 'Secure & Private', f6Desc: 'All processing happens in your browser - no data stored' },
    types: { title: '35+ QR Code Types', subtitle: 'Support for every QR code type you could need' },
    why: { title: 'Why Choose Us?', w1Title: '100% Private', w1Desc: 'All processing happens in your browser. No data is sent to our servers.', w2Title: 'Lightning Fast', w2Desc: 'Generate QR codes instantly with real-time preview updates.', w3Title: 'No Registration', w3Desc: 'Start generating QR codes immediately without creating an account.', w4Title: 'Fully Customizable', w4Desc: 'Control every aspect of your QR code design and appearance.', w5Title: 'Multiple Formats', w5Desc: 'Download in PNG, JPEG, SVG, PDF, or high-resolution formats.', w6Title: 'Professional Grade', w6Desc: 'Create print-ready QR codes for professional use.' },
    faq: { title: 'Frequently Asked Questions', subtitle: 'Find answers to common questions about our QR code generator', q1: 'Is my data stored anywhere?', a1: "No, all QR code generation happens entirely in your browser. We don't store or transmit any of your data to our servers. Your payment status is stored safely in your local browser storage.", q2: 'Can I use these QR codes commercially?', a2: 'Yes, absolutely. You can use QR codes generated here for any purpose - personal, commercial, or otherwise. They never expire.', q3: 'Is this completely free?', a3: 'Your first 3 QR code generations are 100% free. After that, we charge a tiny one-time fee of ₦1,000 for lifetime unlimited access to all features, including logo uploads. No monthly subscriptions.', q4: 'Do I need to create an account?', a4: 'No account needed! Even when paying the one-time ₦1,000 fee, you just enter your email for the receipt. Your access is tied to your browser instantly.', q5: 'Can I customize the appearance of QR codes?', a5: 'Yes, you can customize colors, sizes, error correction levels, margins, and upload your own logo to be centered on the QR code.', q6: "What's the maximum QR code size?", a6: 'You can generate QR codes up to 1000x1000 pixels. For print quality, we recommend downloading as PNG at the highest size setting.' },
    cta: { title: 'Ready to Create Your QR Code?', subtitle: 'Start generating professional QR codes in seconds', btn: 'Get Started Now' },
    footer: { tagline: 'Professional QR code generation made simple.', product: 'Product', generator: 'Generator', resources: 'Resources', documentation: 'Documentation', legal: 'Legal', pricing: 'Pricing', privacy: 'Privacy Policy', terms: 'Terms of Service', copyright: '© 2026 KennyKentola Digital QR Code Generator. All rights reserved.' },
    generator: {
      title: 'QR Code Generator', subtitle: 'Create professional QR codes instantly with advanced customization', unlimited: 'Unlimited Access', free_left: 'free generations left', free_left_single: 'free generation left',
      qr_type: 'QR Type', content: 'Content', customization: 'Customization', tab_colors: 'Colors', tab_style: 'Style', tab_size: 'Size', tab_logo: 'Logo', fg_color: 'Foreground Color', bg_color: 'Background Color',
      err_corr: 'Error Correction Level', err_l: 'Low (7%) — smaller QR', err_m: 'Medium (15%)', err_q: 'Quartile (25%)', err_h: 'High (30%) — best with logo', margin: 'Margin', modules: 'modules', size: 'Size',
      dropzone: 'Drag & drop your logo here, or click to select', dropzone_hint: 'Supports PNG, JPG, WEBP (Max 2MB)', upload_logo: 'Upload logo', logo_preview: 'Logo preview', logo_loaded: 'Logo loaded ✓', drop_logo: 'Drop your logo here', logo_formats: 'PNG, JPG, SVG supported', or_url: 'Or enter image URL', logo_size: 'Logo Size', remove_logo: 'Remove Logo', generating: 'Generating...',
      waiting: 'Waiting for input to generate QR code', fill_in: 'Fill in the content to generate your QR code', limit_reached: 'Limit Reached', limit_desc: 'Pay ₦1,000 to unlock this QR code and unlimited generations.',
      unlock_btn: 'Unlock Now', unlock_unlimited: 'Unlock Unlimited — Pay ₦1,000', copy: 'Copy', share: 'Share', reset: 'Reset All', free_remaining_1: 'of 3 free generations remaining — pay ₦1,000 for unlimited access', free_remaining_2: 'Free limit reached — pay ₦1,000 to unlock unlimited QR codes'
    },
    scanner: {
      title: 'QR Code Scanner & Decoder', subtitle: 'Scan with your camera or upload an image — results appear instantly',
      live_cam: 'Live Camera Scanner', cam_preview: 'Camera preview will appear here', scanning: 'Scanning…', stop_cam: 'Stop Camera', start_cam: 'Start Camera',
      upload_img: 'Upload Image', click_upload: 'Click to upload an image', formats: 'PNG, JPG, WEBP supported', choose_img: 'Choose Image',
      decoded: 'Decoded Content', open_link: 'Open link ↗', copy_res: 'Copy Result', clear: 'Clear',
      private_title: '100% Private Scanning', private_desc: 'All scanning happens directly in your browser. Your camera feed and uploaded images are never sent to any server. For best results when uploading, ensure the QR code is clear, well-lit, and fills a good portion of the image.',
      toast_detected: 'QR code detected!', toast_decoded: 'QR code successfully decoded!', toast_not_found: 'No QR code found. Please try a clearer image.', toast_analyze_fail: 'Failed to analyze image', toast_process_fail: 'Failed to process image', toast_copied: 'Copied to clipboard', toast_copy_fail: 'Failed to copy',
      cam_error_perm: 'Camera permission denied. Please allow camera access in your browser settings.', cam_error_acc: 'Could not access camera. Please ensure a camera is connected.'
    }
  },
  es: {
    about: {"title":"Acerca del Generador QR","subtitle":"Nuestra misión es hacer la generación de códigos QR simple, rápida y accesible","mission":"Nuestra Misión","m1":"Creemos que los códigos QR deben ser accesibles para todos. Nuestra plataforma proporciona una forma gratuita, rápida y segura de generar códigos QR.","m2":"Ya sea que sea dueño de un pequeño negocio, comercializador o desarrollador, nuestra herramienta facilita la creación de códigos QR para cualquier propósito.","values":"Nuestros Valores","v1Title":"El Usuario Primero","v1Desc":"Priorizamos la experiencia del usuario y hacemos que nuestras herramientas sean intuitivas.","v2Title":"Rendimiento","v2Desc":"Generación ultrarrápida y vista previa en tiempo real para la mejor experiencia.","v3Title":"Privacidad","v3Desc":"Todo el procesamiento ocurre en su navegador. Nunca almacenamos sus datos.","v4Title":"Accesibilidad","v4Desc":"Uso gratuito, sin necesidad de registro, accesible desde cualquier lugar.","why":"¿Por qué Elegirnos?","w1":"Soporte para más de 35 tipos de códigos QR","w2":"Opciones avanzadas de personalización","w3":"Múltiples formatos de exportación","w4":"Vista previa en tiempo real","w5":"100% gratis y sin registro","w6":"Completamente privado: procesamiento en el navegador"},
    faq_page: {"title":"Preguntas Frecuentes","subtitle":"Encuentre respuestas a preguntas comunes sobre el Generador QR","q1":"¿Es gratis usar el Generador QR?","a1":"Sus primeras 3 generaciones son completamente gratuitas. Después de eso, cobramos una pequeña tarifa única de ₦1,000 para acceso ilimitado de por vida.","q2":"¿Necesito crear una cuenta?","a2":"No, no necesita crear una cuenta. Incluso al pagar, solo ingresa su correo electrónico para el recibo.","q3":"¿Se almacenan mis datos en sus servidores?","a3":"No, toda la generación de códigos QR ocurre en su navegador. No almacenamos datos.","q4":"¿Qué tipos de códigos QR son compatibles?","a4":"Soportamos más de 35 tipos de códigos QR, incluyendo URL, correos, WiFi, vCards y más.","q5":"¿Puedo personalizar la apariencia de los códigos QR?","a5":"Sí, puede personalizar colores, tamaños, nivel de corrección de errores, márgenes y logotipos.","q6":"¿En qué formatos puedo descargar los códigos QR?","a6":"Puede descargar códigos QR como PNG, JPEG, SVG y PDF.","q7":"¿Puedo usar estos códigos QR comercialmente?","a7":"Sí, absolutamente. Puede usarlos para cualquier propósito.","q8":"¿Cómo escaneo un código QR?","a8":"La mayoría de los teléfonos tienen escáner integrado. Para otros dispositivos, use nuestra herramienta Escáner QR.","q9":"¿Qué es el nivel de corrección de errores?","a9":"Determina cuánto del código QR puede dañarse mientras sigue siendo escaneable.","q10":"¿Puedo editar un código QR después de generarlo?","a10":"Puede regenerarlo con diferentes configuraciones, pero los códigos QR son estáticos una vez creados."},
    pricing_page: {"title":"Precios Simples y Transparentes","subtitle":"Pruébelo gratis, luego pague una vez por acceso ilimitado.","free":"Prueba Gratuita","free_price":"₦0","free_sub":"Los primeros 3 códigos QR corren por nuestra cuenta","f1":"Hasta 3 generaciones de códigos QR","f2":"Más de 35 tipos de códigos QR","f3":"Descargas PNG y JPEG","f4":"Colores y estilos personalizados","f5":"Soporte de carga de logotipo","start_free":"Iniciar Prueba Gratuita","premium":"Acceso Ilimitado","premium_price":"₦1,000","premium_sub":"Pago único, acceso de por vida","p1":"Generaciones ilimitadas","p2":"Todos los 35+ tipos de códigos QR","p3":"PNG de alta resolución, JPEG, SVG y PDF","p4":"Personalización avanzada","p5":"Soporte premium de logotipos","p6":"Sin suscripciones mensuales","get_unlimited":"Obtener Acceso Ilimitado"},
    contact: {"title":"Contáctenos","subtitle":"Nos encantaría saber de usted","get_in_touch":"Póngase en Contacto","desc":"¿Tiene alguna pregunta o sugerencia? Estamos aquí para ayudar. Envíenos un mensaje y responderemos lo antes posible.","email":"Correo","phone":"Teléfono","address":"Dirección","form_name":"Nombre","form_name_ph":"Su nombre","form_email":"Correo","form_email_ph":"su@correo.com","form_subject":"Asunto","form_subject_ph":"¿Cómo podemos ayudar?","form_message":"Mensaje","form_message_ph":"Su mensaje...","send":"Enviar Mensaje","success":"¡Gracias por su mensaje! Nos pondremos en contacto pronto."},

    nav: { scanner: 'Escáner', templates: 'Plantillas', blog: 'Blog', docs: 'Documentación', about: 'Acerca de', contact: 'Contacto', getStarted: 'Empezar' },
    blog: { title: 'Recursos y Tutoriales', subtitle: 'Domine el arte de los códigos QR para su negocio con nuestras guías.', read_article: 'Leer Artículo', back: '← Volver a Recursos' },
    hero: { title: 'Códigos QR profesionales en segundos', subtitle: 'Cree hermosos códigos QR personalizables con soporte de logotipo. Sus primeros 3 códigos son 100% gratuitos, sin registro.', createBtn: 'Crear Código QR', scanBtn: 'Escanear Código QR', preview: 'Vista previa del Código QR' },
    features: { title: 'Funciones Potentes', subtitle: 'Todo lo que necesita para crear códigos QR profesionales con personalización avanzada', f1Title: '35+ Tipos de QR', f1Desc: 'Genere códigos QR para URLs, correos, WiFi, vCard, pagos, redes sociales y más', f2Title: 'Personalización Avanzada', f2Desc: 'Control total sobre colores, estilos, colocación del logotipo y diseños de marco', f3Title: 'Múltiples Formatos', f3Desc: 'Exporte como PNG, SVG, JPEG, PDF o alta resolución para imprimir', f4Title: 'Vista Previa en Tiempo Real', f4Desc: 'Vea los cambios al instante mientras personaliza su código QR', f5Title: 'Optimizado para Móviles', f5Desc: 'Funciona perfectamente en todos los dispositivos con diseño responsivo', f6Title: 'Seguro y Privado', f6Desc: 'Todo el procesamiento ocurre en su navegador, sin datos almacenados' },
    types: { title: '35+ Tipos de Código QR', subtitle: 'Soporte para cada tipo de código QR que pueda necesitar' },
    why: { title: '¿Por qué Elegirnos?', w1Title: '100% Privado', w1Desc: 'Todo el procesamiento ocurre en su navegador. No se envían datos a nuestros servidores.', w2Title: 'Rapidísimo', w2Desc: 'Genere códigos QR al instante con vista previa en tiempo real.', w3Title: 'Sin Registro', w3Desc: 'Comience a generar códigos QR inmediatamente sin crear una cuenta.', w4Title: 'Totalmente Personalizable', w4Desc: 'Controle cada aspecto del diseño y apariencia de su código QR.', w5Title: 'Múltiples Formatos', w5Desc: 'Descargue en PNG, JPEG, SVG, PDF o formatos de alta resolución.', w6Title: 'Calidad Profesional', w6Desc: 'Cree códigos QR listos para imprimir para uso profesional.' },
    faq: { title: 'Preguntas Frecuentes', subtitle: 'Encuentre respuestas a preguntas comunes sobre nuestro generador de códigos QR', q1: '¿Se almacenan mis datos en algún lugar?', a1: 'No, toda la generación de códigos QR ocurre completamente en su navegador. No almacenamos ni transmitimos ninguno de sus datos a nuestros servidores.', q2: '¿Puedo usar estos códigos QR comercialmente?', a2: 'Sí, absolutamente. Puede usar los códigos QR generados aquí para cualquier propósito: personal, comercial o de otro tipo. Nunca expiran.', q3: '¿Es esto completamente gratis?', a3: 'Sus primeras 3 generaciones de códigos QR son 100% gratuitas. Después, cobramos una pequeña tarifa única de ₦1,000 para acceso ilimitado de por vida.', q4: '¿Necesito crear una cuenta?', a4: '¡No se necesita cuenta! Incluso al pagar la tarifa única de ₦1,000, solo ingresa su correo electrónico para el recibo.', q5: '¿Puedo personalizar la apariencia de los códigos QR?', a5: 'Sí, puede personalizar colores, tamaños, niveles de corrección de errores, márgenes y subir su propio logotipo.', q6: '¿Cuál es el tamaño máximo del código QR?', a6: 'Puede generar códigos QR de hasta 1000x1000 píxeles. Para calidad de impresión, recomendamos descargar como PNG al tamaño más alto.' },
    cta: { title: '¿Listo para Crear su Código QR?', subtitle: 'Comience a generar códigos QR profesionales en segundos', btn: 'Comenzar Ahora' },
    footer: { tagline: 'Generación profesional de códigos QR simplificada.', product: 'Producto', generator: 'Generador', resources: 'Recursos', documentation: 'Documentación', legal: 'Legal', pricing: 'Precios', privacy: 'Política de Privacidad', terms: 'Términos de Servicio', copyright: '© 2026 KennyKentola Digital QR Code Generator. Todos los derechos reservados.' },
    generator: {
      title: 'Generador de Códigos QR', subtitle: 'Cree códigos QR profesionales al instante con personalización avanzada', unlimited: 'Acceso Ilimitado', free_left: 'generaciones gratuitas restantes', free_left_single: 'generación gratuita restante',
      qr_type: 'Tipo de QR', content: 'Contenido', customization: 'Personalización', tab_colors: 'Colores', tab_style: 'Estilo', tab_size: 'Tamaño', tab_logo: 'Logo', fg_color: 'Color de primer plano', bg_color: 'Color de fondo',
      err_corr: 'Nivel de corrección de errores', err_l: 'Bajo (7%) — QR más pequeño', err_m: 'Medio (15%)', err_q: 'Cuartil (25%)', err_h: 'Alto (30%) — mejor con logo', margin: 'Margen', modules: 'módulos', size: 'Tamaño',
      dropzone: 'Arrastre y suelte su logotipo aquí, o haga clic para seleccionar', dropzone_hint: 'Soporta PNG, JPG, WEBP (Max 2MB)', or_url: 'O ingrese la URL de la imagen', logo_size: 'Tamaño del logotipo', remove_logo: 'Eliminar logotipo', generating: 'Generando...',
      waiting: 'Esperando entrada para generar el código QR', fill_in: 'Complete el contenido para generar su código QR', limit_reached: 'Límite Alcanzado', limit_desc: 'Pague ₦1,000 para desbloquear este código QR y generaciones ilimitadas.',
      unlock_btn: 'Desbloquear Ahora', unlock_unlimited: 'Desbloquear Ilimitado — Pagar ₦1,000', copy: 'Copiar', share: 'Compartir', reset: 'Restablecer Todo', free_remaining_1: 'de 3 generaciones gratuitas restantes — pague ₦1,000 para acceso ilimitado', free_remaining_2: 'Límite gratuito alcanzado — pague ₦1,000 para desbloquear códigos QR ilimitados'
    },
    scanner: {
      title: 'Escáner y Decodificador de Códigos QR', subtitle: 'Escanee con su cámara o suba una imagen — los resultados aparecen al instante',
      live_cam: 'Escáner de Cámara en Vivo', cam_preview: 'La vista previa de la cámara aparecerá aquí', scanning: 'Escaneando…', stop_cam: 'Detener Cámara', start_cam: 'Iniciar Cámara',
      upload_img: 'Subir Imagen', click_upload: 'Haga clic para subir una imagen', formats: 'Soporta PNG, JPG, WEBP', choose_img: 'Elegir Imagen',
      decoded: 'Contenido Decodificado', open_link: 'Abrir enlace ↗', copy_res: 'Copiar Resultado', clear: 'Limpiar',
      private_title: 'Escaneo 100% Privado', private_desc: 'Todo el escaneo ocurre directamente en su navegador. Su cámara y las imágenes subidas nunca se envían a ningún servidor. Para mejores resultados al subir, asegúrese de que el código QR sea claro, esté bien iluminado y ocupe una buena parte de la imagen.',
      toast_detected: '¡Código QR detectado!', toast_decoded: '¡Código QR decodificado exitosamente!', toast_not_found: 'No se encontró ningún código QR. Por favor intente con una imagen más clara.', toast_analyze_fail: 'Error al analizar la imagen', toast_process_fail: 'Error al procesar la imagen', toast_copied: 'Copiado al portapapeles', toast_copy_fail: 'Error al copiar',
      cam_error_perm: 'Permiso de cámara denegado. Por favor permita el acceso a la cámara en la configuración de su navegador.', cam_error_acc: 'No se pudo acceder a la cámara. Por favor asegúrese de que haya una cámara conectada.'
    }
  },
  fr: {
    about: {"title":"À propos du Générateur QR","subtitle":"Notre mission est de rendre la génération de codes QR simple, rapide et accessible","mission":"Notre Mission","m1":"Nous pensons que les codes QR doivent être accessibles à tous. Notre plateforme offre un moyen gratuit, rapide et sécurisé de générer des codes QR.","m2":"Que vous soyez propriétaire d'entreprise, spécialiste du marketing ou développeur, notre outil facilite la création de codes QR.","values":"Nos Valeurs","v1Title":"L'utilisateur d'abord","v1Desc":"Nous priorisons l'expérience utilisateur.","v2Title":"Performance","v2Desc":"Génération ultra-rapide et aperçu en temps réel.","v3Title":"Confidentialité","v3Desc":"Tout le traitement se fait dans votre navigateur. Nous ne stockons jamais vos données.","v4Title":"Accessibilité","v4Desc":"Gratuit, sans inscription, accessible partout.","why":"Pourquoi nous choisir ?","w1":"Plus de 35 types de codes QR","w2":"Options de personnalisation avancées","w3":"Multiples formats d'exportation","w4":"Aperçu en temps réel","w5":"100% gratuit et sans inscription","w6":"Entièrement privé - traitement dans le navigateur"},
    faq_page: {"title":"Questions Fréquemment Posées","subtitle":"Trouvez des réponses aux questions courantes sur le Générateur QR","q1":"Est-ce gratuit d'utiliser le Générateur QR ?","a1":"Vos 3 premières générations sont 100 % gratuites. Ensuite, nous facturons ₦1,000 pour un accès illimité à vie.","q2":"Dois-je créer un compte ?","a2":"Non, aucune inscription n'est requise.","q3":"Mes données sont-elles stockées sur vos serveurs ?","a3":"Non, tout se passe dans votre navigateur.","q4":"Quels types de codes QR sont pris en charge ?","a4":"Plus de 35 types, dont URL, emails, WiFi, etc.","q5":"Puis-je personnaliser les codes QR ?","a5":"Oui, couleurs, taille, marge, et logos.","q6":"Dans quels formats puis-je télécharger ?","a6":"PNG, JPEG, SVG et PDF.","q7":"Puis-je utiliser ces codes commercialement ?","a7":"Oui, absolument.","q8":"Comment scanner un code QR ?","a8":"Utilisez l'appareil photo de votre smartphone ou notre outil de scanner.","q9":"Qu'est-ce que le niveau de correction d'erreur ?","a9":"Il détermine combien le code peut être endommagé tout en restant lisible.","q10":"Puis-je modifier un code QR ?","a10":"Les codes QR sont statiques une fois créés. Générez-en un nouveau."},
    pricing_page: {"title":"Tarification Simple","subtitle":"Essayez-le gratuitement, puis payez une fois pour un accès illimité.","free":"Essai Gratuit","free_price":"₦0","free_sub":"Les 3 premiers codes QR sont offerts","f1":"Jusqu'à 3 générations","f2":"Plus de 35 types de QR","f3":"Téléchargements PNG et JPEG","f4":"Couleurs et styles personnalisés","f5":"Prise en charge des logos","start_free":"Démarrer l'essai gratuit","premium":"Accès Illimité","premium_price":"₦1,000","premium_sub":"Paiement unique, accès à vie","p1":"Générations illimitées","p2":"Tous les 35+ types de QR","p3":"PNG HD, JPEG, SVG et PDF","p4":"Personnalisation avancée","p5":"Logos premium","p6":"Sans abonnement mensuel","get_unlimited":"Obtenir un accès illimité"},
    contact: {"title":"Contactez-nous","subtitle":"Nous aimerions avoir de vos nouvelles","get_in_touch":"Prendre Contact","desc":"Vous avez une question ou une suggestion ? Envoyez-nous un message.","email":"Email","phone":"Téléphone","address":"Adresse","form_name":"Nom","form_name_ph":"Votre nom","form_email":"Email","form_email_ph":"votre@email.com","form_subject":"Sujet","form_subject_ph":"Comment pouvons-nous aider ?","form_message":"Message","form_message_ph":"Votre message...","send":"Envoyer","success":"Merci pour votre message ! Nous vous répondrons bientôt."},

    nav: { scanner: 'Scanner', templates: 'Modèles', blog: 'Blog', docs: 'Documentation', about: 'À propos', contact: 'Contact', getStarted: 'Commencer' },
    blog: { title: 'Ressources et Tutoriels', subtitle: 'Maîtrisez l\'art des codes QR pour votre entreprise avec nos guides.', read_article: 'Lire l\'Article', back: '← Retour aux Ressources' },
    hero: { title: 'Codes QR professionnels en quelques secondes', subtitle: 'Créez de superbes codes QR personnalisables avec prise en charge des logos. Vos 3 premiers codes sont 100 % gratuits, sans inscription.', createBtn: 'Créer un Code QR', scanBtn: 'Scanner un Code QR', preview: 'Aperçu du Code QR' },
    features: { title: 'Fonctionnalités Puissantes', subtitle: 'Tout ce dont vous avez besoin pour créer des codes QR professionnels avec une personnalisation avancée', f1Title: '35+ Types de QR', f1Desc: 'Générez des codes QR pour les URL, e-mails, WiFi, vCard, paiements, réseaux sociaux et plus', f2Title: 'Personnalisation Avancée', f2Desc: 'Contrôle total sur les couleurs, styles, placement du logo et designs de cadre', f3Title: 'Formats Multiples', f3Desc: 'Exportez en PNG, SVG, JPEG, PDF ou haute résolution pour impression', f4Title: 'Aperçu en Temps Réel', f4Desc: 'Voyez les changements instantanément pendant la personnalisation de votre code QR', f5Title: 'Optimisé pour Mobile', f5Desc: 'Fonctionne parfaitement sur tous les appareils avec un design responsive', f6Title: 'Sécurisé et Privé', f6Desc: 'Tout le traitement se fait dans votre navigateur, aucune donnée stockée' },
    types: { title: '35+ Types de Code QR', subtitle: 'Prise en charge de tous les types de codes QR dont vous avez besoin' },
    why: { title: 'Pourquoi Nous Choisir ?', w1Title: '100% Privé', w1Desc: 'Tout le traitement se fait dans votre navigateur. Aucune donnée envoyée à nos serveurs.', w2Title: 'Ultra Rapide', w2Desc: 'Générez des codes QR instantanément avec un aperçu en temps réel.', w3Title: 'Sans Inscription', w3Desc: 'Commencez à générer des codes QR immédiatement sans créer de compte.', w4Title: 'Entièrement Personnalisable', w4Desc: 'Contrôlez chaque aspect du design et de l\'apparence de votre code QR.', w5Title: 'Formats Multiples', w5Desc: 'Téléchargez en PNG, JPEG, SVG, PDF ou en haute résolution.', w6Title: 'Qualité Professionnelle', w6Desc: 'Créez des codes QR prêts à imprimer pour un usage professionnel.' },
    faq: { title: 'Questions Fréquemment Posées', subtitle: 'Trouvez des réponses aux questions courantes sur notre générateur de codes QR', q1: 'Mes données sont-elles stockées quelque part ?', a1: 'Non, toute la génération de codes QR se fait entièrement dans votre navigateur. Nous ne stockons ni ne transmettons aucune de vos données.', q2: 'Puis-je utiliser ces codes QR à des fins commerciales ?', a2: 'Oui, absolument. Vous pouvez utiliser les codes QR générés ici pour tout usage personnel, commercial ou autre. Ils n\'expirent jamais.', q3: 'Est-ce complètement gratuit ?', a3: 'Vos 3 premières générations de codes QR sont 100% gratuites. Ensuite, nous facturons un petit frais unique de ₦1,000 pour un accès illimité à vie.', q4: 'Dois-je créer un compte ?', a4: 'Aucun compte nécessaire ! Même en payant le frais unique de ₦1,000, vous entrez simplement votre e-mail pour le reçu.', q5: 'Puis-je personnaliser l\'apparence des codes QR ?', a5: 'Oui, vous pouvez personnaliser les couleurs, tailles, niveaux de correction d\'erreur, marges et télécharger votre propre logo.', q6: 'Quelle est la taille maximale du code QR ?', a6: 'Vous pouvez générer des codes QR jusqu\'à 1000x1000 pixels. Pour la qualité d\'impression, nous recommandons de télécharger en PNG à la taille maximale.' },
    cta: { title: 'Prêt à Créer Votre Code QR ?', subtitle: 'Commencez à générer des codes QR professionnels en quelques secondes', btn: 'Commencer Maintenant' },
    footer: { tagline: 'Génération professionnelle de codes QR simplifiée.', product: 'Produit', generator: 'Générateur', resources: 'Ressources', documentation: 'Documentation', legal: 'Juridique', pricing: 'Tarifs', privacy: 'Politique de Confidentialité', terms: 'Conditions d\'Utilisation', copyright: '© 2026 KennyKentola Digital QR Code Generator. Tous droits réservés.' },
    generator: {
      title: 'Générateur de Code QR', subtitle: 'Créez des codes QR professionnels instantanément avec une personnalisation avancée', unlimited: 'Accès Illimité', free_left: 'générations gratuites restantes', free_left_single: 'génération gratuite restante',
      qr_type: 'Type de QR', content: 'Contenu', customization: 'Personnalisation', tab_colors: 'Couleurs', tab_style: 'Style', tab_size: 'Taille', tab_logo: 'Logo', fg_color: 'Couleur de premier plan', bg_color: 'Couleur de fond',
      err_corr: 'Niveau de correction d\'erreur', err_l: 'Faible (7%) — QR plus petit', err_m: 'Moyen (15%)', err_q: 'Quartile (25%)', err_h: 'Élevé (30%) — meilleur avec logo', margin: 'Marge', modules: 'modules', size: 'Taille',
      dropzone: 'Glissez-déposez votre logo ici, ou cliquez pour sélectionner', dropzone_hint: 'Prend en charge PNG, JPG, WEBP (Max 2 Mo)', or_url: 'Ou entrez l\'URL de l\'image', logo_size: 'Taille du logo', remove_logo: 'Supprimer le logo', generating: 'Génération...',
      waiting: 'En attente d\'entrée pour générer le code QR', fill_in: 'Remplissez le contenu pour générer votre code QR', limit_reached: 'Limite Atteinte', limit_desc: 'Payez ₦1,000 pour débloquer ce code QR et des générations illimitées.',
      unlock_btn: 'Débloquer Maintenant', unlock_unlimited: 'Débloquer Illimité — Payer ₦1,000', copy: 'Copier', share: 'Partager', reset: 'Tout Réinitialiser', free_remaining_1: 'sur 3 générations gratuites restantes — payez ₦1,000 pour un accès illimité', free_remaining_2: 'Limite gratuite atteinte — payez ₦1,000 pour débloquer des codes QR illimités'
    },
    scanner: {
      title: 'Scanner et Décodeur de Code QR', subtitle: 'Scannez avec votre caméra ou téléchargez une image — les résultats apparaissent instantanément',
      live_cam: 'Scanner de Caméra en Direct', cam_preview: 'L\'aperçu de la caméra apparaîtra ici', scanning: 'Numérisation…', stop_cam: 'Arrêter la Caméra', start_cam: 'Démarrer la Caméra',
      upload_img: 'Télécharger une Image', click_upload: 'Cliquez pour télécharger une image', formats: 'Prise en charge PNG, JPG, WEBP', choose_img: 'Choisir une Image',
      decoded: 'Contenu Décodé', open_link: 'Ouvrir le lien ↗', copy_res: 'Copier le Résultat', clear: 'Effacer',
      private_title: 'Numérisation 100% Privée', private_desc: 'Toute la numérisation s\'effectue directement dans votre navigateur. Votre flux de caméra et vos images téléchargées ne sont jamais envoyés à aucun serveur. Pour de meilleurs résultats lors du téléchargement, assurez-vous que le code QR est clair, bien éclairé et occupe une bonne partie de l\'image.',
      toast_detected: 'Code QR détecté !', toast_decoded: 'Code QR décodé avec succès !', toast_not_found: 'Aucun code QR trouvé. Veuillez essayer une image plus claire.', toast_analyze_fail: 'Échec de l\'analyse de l\'image', toast_process_fail: 'Échec du traitement de l\'image', toast_copied: 'Copié dans le presse-papiers', toast_copy_fail: 'Échec de la copie',
      cam_error_perm: 'Autorisation de caméra refusée. Veuillez autoriser l\'accès à la caméra dans les paramètres de votre navigateur.', cam_error_acc: 'Impossible d\'accéder à la caméra. Veuillez vous assurer qu\'une caméra est connectée.'
    }
  },
  yo: {
    about: {"title":"Nípa Ẹrọ Ṣíṣẹ̀dá QR","subtitle":"Iṣẹ́ wa ni láti jẹ́ kí ṣíṣẹ̀dá koodu QR rọrùn, yára, kí ó sì wà fún gbogbo ènìyàn","mission":"Iṣẹ́ Wa","m1":"A gbàgbọ́ pé koodu QR yẹ kí ó wà fún gbogbo ènìyàn. A pèsè ọ̀nà ọ̀fẹ́, yára àti ààbò fún gbogbo ènìyàn.","m2":"Yálà o jẹ́ oníṣòwò tàbí oníṣẹ́-ẹ̀rọ, ẹ̀rọ wa sọ ṣíṣẹ̀dá QR di ìrọ̀rùn.","values":"Àwọn Ohun Tí A Níyelórí","v1Title":"Oníbàárà Lákọ̀ọ́kọ́","v1Desc":"A fẹ́ kí o jẹ ìgbádùn lílo ẹ̀rọ wa.","v2Title":"Ìyára","v2Desc":"Ó yára bíi mọ̀nàmọ́ná.","v3Title":"Àṣírí","v3Desc":"Kò sí dátà rẹ tí a tọ́jú sí ibikíbi.","v4Title":"Ìrọ̀rùn","v4Desc":"Ọ̀fẹ́ ni, kò sí ìforúkọsílẹ̀.","why":"Kí nìdí tí o fi yẹ kí o yàn wá?","w1":"Oríṣi koodu QR 35+","w2":"Àtúnṣe tó péye","w3":"Fọ́mátì púpọ̀","w4":"Àwòté ìsinsìnyí","w5":"Ọ̀fẹ́ 100%","w6":"Àṣírí pátápátá"},
    faq_page: {"title":"Àwọn Ìbéèrè Lóòrèkóòrè","subtitle":"Wa ìdáhùn sí àwọn ìbéèrè nipa Ẹrọ QR","q1":"Ṣé Ẹrọ QR jẹ́ ọ̀fẹ́?","a1":"Mẹ́ta àkọ́kọ́ jẹ́ ọ̀fẹ́. Lẹ́yìn náà, san ₦1,000 fún lílò tí kò lópin.","q2":"Ṣé mo nílò àkọọnti?","a2":"Rárá, o kò nílò àkọọnti.","q3":"Ṣé dátà mi wà níbìkan?","a3":"Rárá, a kò tọ́jú dátà rẹ.","q4":"Àwọn koodu QR wo ni o wà?","a4":"A ní oríṣi 35+ títí kan URL, WiFi, àti bẹ́ẹ̀ bẹ́ẹ̀ lọ.","q5":"Ṣé mo le ṣe àtúnṣe rẹ̀?","a5":"Bẹ́ẹ̀ni, o le yi àwọ̀ àti àmì rẹ padà.","q6":"Àwọn fọ́mátì wo ni o wà?","a6":"O le gba PNG, JPEG, SVG, àti PDF.","q7":"Ṣé mo le lò ó fún iṣẹ́?","a7":"Bẹ́ẹ̀ni, o le lò ó fún ohunkóhun.","q8":"Báwo ni mo ṣe le ṣàyẹ̀wò koodu QR?","a8":"Lo kámẹ́rà foonu rẹ tàbí Ẹrọ Ayẹwo wa.","q9":"Kí ni àtúnṣe àṣìṣe?","a9":"Ó fihàn bí koodu rẹ ṣe le ṣiṣẹ́ tó bí ó bá bajẹ́ díẹ̀.","q10":"Ṣé mo le ṣe àtúnṣe koodu lẹ́yìn tí mo ti ṣẹ̀dá rẹ̀?","a10":"Koodu QR kì í yipadà. O gbọ́dọ̀ ṣẹ̀dá òmíràn."},
    pricing_page: {"title":"Iye Owó Tó Mọ́yánmọ́","subtitle":"Lò ó lọ́fẹ̀ẹ́, lẹ́yìn náà sanwó ẹ̀ẹ̀kan fún lílò tí kò lópin.","free":"Ìdánwò Ọ̀fẹ́","free_price":"₦0","free_sub":"Koodu QR 3 àkọ́kọ́ jẹ́ ọ̀fẹ́","f1":"Ṣẹ̀dá koodu 3","f2":"Oríṣi koodu QR 35+","f3":"PNG àti JPEG","f4":"Àwọ̀ àti ara","f5":"Fifi àmì síi","start_free":"Bẹ̀rẹ̀ Ìdánwò","premium":"Lílò Tí Kò Lópin","premium_price":"₦1,000","premium_sub":"Sanwó ẹ̀ẹ̀kan soso","p1":"Ṣẹ̀dá koodu àìmọye","p2":"Gbogbo oríṣi 35+","p3":"PNG, JPEG, SVG àti PDF","p4":"Àtúnṣe ẹ̀kúnrẹ́rẹ́","p5":"Àmì àkànṣe","p6":"Kò sí owó oṣooṣù","get_unlimited":"Gba Lílò Tí Kò Lópin"},
    contact: {"title":"Kàn Sí Wa","subtitle":"A fẹ́ gbọ́ láti ọ̀dọ̀ rẹ","get_in_touch":"Bá wa sọ̀rọ̀","desc":"Ṣé o ní ìbéèrè tàbí àbá? Fi àtẹ̀jísẹ́ ránṣẹ́ sí wa.","email":"Imeeli","phone":"Foonu","address":"Àdírẹ́sì","form_name":"Orúkọ","form_name_ph":"Orúkọ rẹ","form_email":"Imeeli","form_email_ph":"imeeli@tiẹ.com","form_subject":"Orí-ọ̀rọ̀","form_subject_ph":"Báwo ni a ṣe le ràn ọ́ lọ́wọ́?","form_message":"Àtẹ̀jísẹ́","form_message_ph":"Àtẹ̀jísẹ́ rẹ...","send":"Fi Ránṣẹ́","success":"A ti rí àtẹ̀jísẹ́ rẹ! A óò kàn sí ọ láìpẹ́."},

    nav: { scanner: 'Ẹrọ Ayẹwo', templates: 'Àwọn Àwòṣe', blog: 'Búlọ̀ọ̀gù', docs: 'Àwọn Ìwé', about: 'Nípa Wa', contact: 'Kàn sí wa', getStarted: 'Bẹ̀rẹ̀' },
    blog: { title: 'Àwọn Ohun-èlò & Ìkọ́ni', subtitle: 'Kọ́ bí a ṣe ń lo koodu QR fún iṣẹ́ rẹ pẹ̀lú àwọn ìtọ́sọ́nà wa.', read_article: 'Ka Àkọlé', back: '← Padà sí Àwọn Ohun-èlò' },
    hero: { title: 'Koodu QR Alámọ̀dájú ní Ìṣẹ́jú Aáyá', subtitle: 'Ṣẹ̀dá àwọn koodu QR tó lẹ́wà, pẹ̀lú àtìlẹ́yìn àmì-iṣẹ́. Koodu 3 rẹ àkọ́kọ́ jẹ́ ọ̀fẹ́ 100% — kò sí ìforúkọsílẹ̀.', createBtn: 'Ṣẹ̀dá Koodu QR', scanBtn: 'Ṣàyẹ̀wò Koodu QR', preview: 'Àwòté Koodu QR' },
    features: { title: 'Àwọn Ẹ̀yà Pàtàkì', subtitle: 'Ohun gbogbo tí o nílò láti ṣẹ̀dá àwọn koodu QR alámọ̀dájú', f1Title: '35+ Oríṣi QR', f1Desc: 'Ṣẹ̀dá àwọn koodu QR fún URL, imeeli, WiFi, vCard, sísanwó, àti bẹ́ẹ̀ bẹ́ẹ̀ lọ', f2Title: 'Ìyípadà Àti Àtúnṣe', f2Desc: 'Ìṣàkóso ẹ̀kúnrẹ́rẹ́ lórí àwọ̀, ara, ìfilọ́lẹ̀ àmì, àti àpẹẹrẹ', f3Title: 'Oríṣiríṣi Fọ́mátì', f3Desc: 'Gbé e jáde gẹ́gẹ́ bí PNG, SVG, JPEG, PDF, tàbí gíga-fún-títẹ̀', f4Title: 'Àwòté Ìsinsìnyí', f4Desc: 'Rí àwọn àtúnṣe lẹ́sẹ̀kẹsẹ̀ bí o ṣe ń ṣe àtúnṣe koodu rẹ', f5Title: 'Dára fún Foonu', f5Desc: 'Ó ṣiṣẹ́ dáadáa lórí gbogbo ẹ̀rọ', f6Title: 'Ààbò àti Àṣírí', f6Desc: 'Gbogbo ìṣiṣẹ́ wáyé nínú burausa rẹ - kò sí dátà tí a tọ́jú' },
    types: { title: '35+ Oríṣi Koodu QR', subtitle: 'Àtìlẹ́yìn fún gbogbo oríṣi koodu QR tí o le nílò' },
    why: { title: 'Kí nìdí tí o fi yẹ kí o yàn wá?', w1Title: 'Àṣírí 100%', w1Desc: 'Gbogbo ìṣiṣẹ́ wáyé nínú burausa rẹ. A kò fi dátà kankan ránṣẹ́ sí sérfà wa.', w2Title: 'Yára bíi Mọ̀nàmọ́ná', w2Desc: 'Ṣẹ̀dá àwọn koodu QR lẹ́sẹ̀kẹsẹ̀ pẹ̀lú àwòté ìsinsìnyí.', w3Title: 'Kò sí Ìforúkọsílẹ̀', w3Desc: 'Bẹ̀rẹ̀ sí ṣẹ̀dá àwọn koodu QR lẹ́sẹ̀kẹsẹ̀ láìsí ìdásílẹ̀ àkọọnti.', w4Title: 'Àtúnṣe Ẹ̀kúnrẹ́rẹ́', w4Desc: 'Ṣàkóso gbogbo abala ìrísí àti wíwù koodu QR rẹ.', w5Title: 'Oríṣiríṣi Fọ́mátì', w5Desc: 'Gba wọlé gẹ́gẹ́ bí PNG, JPEG, SVG, PDF tàbí àwọn fọ́mátì gíga.', w6Title: 'Ipò Alámọ̀dájú', w6Desc: 'Ṣẹ̀dá àwọn koodu QR tó ṣetan fún títẹ̀.' },
    faq: { title: 'Àwọn Ìbéèrè Tí A Ń Bèèrè Lóòrèkóòrè', subtitle: 'Rí ìdáhùn sí àwọn ìbéèrè gbogbo nipa ẹ̀rọ QR wa', q1: 'Ṣé dátà mi wa ní ìpamọ́?', a1: "Bẹ́ẹ̀ kọ́, gbogbo rẹ̀ wáyé nínú burausa rẹ. A kò tọ́jú tàbí fi dátà rẹ ránṣẹ́.", q2: 'Ṣé mo le lo àwọn koodu QR wọ̀nyí fún iṣẹ́?', a2: 'Bẹ́ẹ̀ni, dájúdájú. O le lo wọn fún ohunkóhun, wọn kì í parí.', q3: 'Ṣé ọ̀fẹ́ ni pátápátá?', a3: 'Mẹ́ta àkọ́kọ́ jẹ́ ọ̀fẹ́. Lẹ́yìn náà, san ₦1,000 fún lílò tí kò lópin.', q4: 'Ṣé mo nílò àkọọnti?', a4: 'Rárá! Pẹ̀lú owo ₦1,000 náà, imeeli rẹ nìkan ni a nílò fún ìwé-ẹ̀rí.', q5: 'Ṣé mo le ṣe àtúnṣe ìrísí koodu QR?', a5: 'Bẹ́ẹ̀ni, o le yi àwọ̀, ìwọ̀n, àti fi àmì rẹ síi.', q6: "Kí ni ìwọ̀n tí ó pọ̀ jù fún koodu QR?", a6: 'O le ṣẹ̀dá rẹ̀ títí dé 1000x1000 pixels.' },
    cta: { title: 'Ṣé o ti ṣetan láti ṣẹ̀dá Koodu QR rẹ?', subtitle: 'Bẹ̀rẹ̀ sí ṣẹ̀dá àwọn koodu QR alámọ̀dájú ní ìṣẹ́jú aáyá', btn: 'Bẹ̀rẹ̀ Nísinsìnyí' },
    footer: { tagline: 'Ṣíṣẹ̀dá koodu QR alámọ̀dájú ni irọrun.', product: 'Ọjà', generator: 'Ẹrọ Ṣíṣẹ̀dá', resources: 'Àwọn Ohun-èlò', documentation: 'Àwọn Ìwé', legal: 'Òfin', pricing: 'Iye Owó', privacy: 'Ìlànà Àṣírí', terms: 'Àwọn Àdéhùn Iṣẹ́', copyright: '© 2026 KennyKentola Digital QR Code Generator. Gbogbo ẹ̀tọ́ wà ní ìpamọ́.' },
    generator: {
      title: 'Ẹrọ Ṣíṣẹ̀dá Koodu QR', subtitle: 'Ṣẹ̀dá àwọn koodu QR alámọ̀dájú lẹ́sẹ̀kẹsẹ̀', unlimited: 'Lílò Tí Kò Lópin', free_left: 'iṣẹ́ ọ̀fẹ́ tókù', free_left_single: 'iṣẹ́ ọ̀fẹ́ tókù',
      qr_type: 'Oríṣi QR', content: 'Àkóónú', customization: 'Àtúnṣe', tab_colors: 'Àwọ̀', tab_style: 'Ara', tab_size: 'Ìwọ̀n', tab_logo: 'Àmì-iṣẹ́', fg_color: 'Àwọ̀ Iwájú', bg_color: 'Àwọ̀ Ẹ̀yìn',
      err_corr: 'Ìpele Àtúnṣe Àṣìṣe', err_l: 'Kékeré (7%) — QR kéré', err_m: 'Aàrin (15%)', err_q: 'Ìdá Kẹrin (25%)', err_h: 'Gíga (30%) — dára pẹ̀lú àmì', margin: 'Ala', modules: 'modules', size: 'Ìwọ̀n',
      dropzone: 'Fa àmì rẹ sínú ibí, tàbí tẹ̀ láti mu', dropzone_hint: 'Ó ṣe atilẹyin PNG, JPG, WEBP (Max 2MB)', or_url: 'Tàbí kọ URL àwòrán', logo_size: 'Ìwọ̀n Àmì', remove_logo: 'Yọ Àmì', generating: 'Ó ń ṣẹ̀dá...',
      waiting: 'N dúró de àkóónú láti ṣẹ̀dá koodu QR', fill_in: 'Kọ àkóónú láti ṣẹ̀dá koodu QR rẹ', limit_reached: 'Ó ti dé òpin', limit_desc: 'San ₦1,000 láti ṣí koodu QR yí àti lílò tí kò lópin.',
      unlock_btn: 'Ṣí I Nísinsìnyí', unlock_unlimited: 'Ṣí Lílò Tí Kò Lópin — San ₦1,000', copy: 'Dàkọ', share: 'Pín', reset: 'Pa Gbogbo Rẹ Rẹ́', free_remaining_1: 'nínú 3 iṣẹ́ ọ̀fẹ́ tó kù — san ₦1,000 fún lílò tí kò lópin', free_remaining_2: 'Ó ti dé òpin ọ̀fẹ́ — san ₦1,000 láti ṣí lílò tí kò lópin'
    },
    scanner: {
      title: 'Ẹrọ Ayẹwo Koodu QR', subtitle: 'Lo kámẹ́rà rẹ tàbí gbé àwòrán wọlé — yóò fún ọ ní èsì lẹ́sẹ̀kẹsẹ̀',
      live_cam: 'Ẹrọ Ayẹwo Kámẹ́rà Lẹ́sẹ̀kẹsẹ̀', cam_preview: 'Àwòrán kámẹ́rà yóò hàn níhìn-ín', scanning: 'Ó ń ṣàyẹ̀wò…', stop_cam: 'Dúró Kámẹ́rà', start_cam: 'Bẹ̀rẹ̀ Kámẹ́rà',
      upload_img: 'Gbé Àwòrán Wọlé', click_upload: 'Tẹ̀ láti gbé àwòrán wọlé', formats: 'PNG, JPG, WEBP', choose_img: 'Yan Àwòrán',
      decoded: 'Àkóónú Tí A Rí', open_link: 'Ṣí ìjápọ̀ ↗', copy_res: 'Dàkọ Èsì', clear: 'Pa A Rẹ́',
      private_title: 'Àṣírí 100%', private_desc: 'Gbogbo ìṣàyẹ̀wò wáyé nínú burausa rẹ. A kò fi kámẹ́rà tàbí àwòrán rẹ ránṣẹ́ sí sérfà kankan. Fún èsì tó péye, rí i dájú pé koodu QR náà mọ́, o ní ìmọ́lẹ̀, ó sì tóbi.',
      toast_detected: 'A ti rí koodu QR!', toast_decoded: 'A ti túmọ̀ koodu QR!', toast_not_found: 'A kò rí koodu QR kankan. Jọ̀wọ́ lo àwòrán tó mọ́.', toast_analyze_fail: 'A kò le ṣe ìtúpalẹ̀ àwòrán', toast_process_fail: 'A kò le ṣe iṣẹ́ lórí àwòrán', toast_copied: 'A ti dàkọ rẹ̀', toast_copy_fail: 'A kò le dàkọ',
      cam_error_perm: 'A kò fún ọ láàyè kámẹ́rà. Jọ̀wọ́ fún un láàyè nínú burausa rẹ.', cam_error_acc: 'A kò le wọ kámẹ́rà. Jọ̀wọ́ rí i dájú pé kámẹ́rà wà.'
    }
  },
  ha: {
    about: {"title":"Game da Injin QR","subtitle":"Manufarmu ita ce sanya ƙirƙirar QR cikin sauƙi da sauri","mission":"Manufarmu","m1":"Mun yi imanin cewa lambobin QR yakamata kowa ya samesu. Muna bada hanya kyauta kuma mai sauri.","m2":"Ko kai ɗan kasuwa ne ko mai haɓaka manhaja, injin mu yana sauƙaƙa abubuwa.","values":"Kima","v1Title":"Mai Amfani Tukuna","v1Desc":"Muna ba da fifiko ga mai amfani.","v2Title":"Sauri","v2Desc":"Sauri kamar walkiya.","v3Title":"Sirri","v3Desc":"Komai yana faruwa a manhajarka. Ba mu adana bayananka.","v4Title":"Samuwa","v4Desc":"Kyauta don amfani, ba a buƙatar rajista.","why":"Me Yasa Zaku Zabe Mu?","w1":"Irin QR 35+","w2":"Canje-canje na musamman","w3":"Siffofi daban-daban","w4":"Dubawa nan take","w5":"Kyauta 100%","w6":"Sirri 100%"},
    faq_page: {"title":"Tambayoyin Da Ake Yawan Yi","subtitle":"Nemo amsoshi game da Injin QR","q1":"Kyauta ne?","a1":"3 na farko kyauta ne. Bayan haka, muna cajin ₦1,000 don amfani na dindindin.","q2":"Ina buƙatar asusu?","a2":"A'a, ba a buƙatar asusu.","q3":"Kuna adana bayanai na?","a3":"A'a, ba mu adana komai.","q4":"Wadanne irin QR kuke da su?","a4":"Muna da iri 35+ ciki har da URL da WiFi.","q5":"Zan iya gyara lambar QR?","a5":"Eh, zaka iya canza launuka da tambari.","q6":"A wane siffa zan sauke?","a6":"Kuna iya saukewa a PNG, JPEG, SVG, da PDF.","q7":"Zan iya amfani dashi don kasuwanci?","a7":"Eh, tabbas.","q8":"Yaya ake duba QR?","a8":"Yi amfani da kyamarar wayarka ko Injin Duba QR ɗinmu.","q9":"Menene matakin kuskure?","a9":"Yana nuna yadda QR ɗin zai yi aiki ko da ya sami matsala.","q10":"Zan iya canza QR bayan na ƙirƙira?","a10":"A'a, dole ka ƙirƙiri sabo."},
    pricing_page: {"title":"Farashi Mai Sauki","subtitle":"Gwada kyauta, sannan ka biya sau ɗaya.","free":"Gwaji Kyauta","free_price":"₦0","free_sub":"Lambar QR 3 na farko kyauta ne","f1":"Har zuwa ƙirƙira 3","f2":"Irin QR 35+","f3":"Sauke PNG da JPEG","f4":"Launuka da tsari","f5":"Saka tambari","start_free":"Fara Gwaji","premium":"Amfani na Dindindin","premium_price":"₦1,000","premium_sub":"Biyan kuɗi sau ɗaya","p1":"Ƙirƙira marar iyaka","p2":"Duk iri 35+","p3":"PNG, JPEG, SVG & PDF","p4":"Canje-canje babba","p5":"Tambari na musamman","p6":"Babu biyan kuɗin wata-wata","get_unlimited":"Samu Dama Har Abada"},
    contact: {"title":"Tuntube Mu","subtitle":"Muna son jin daga gare ku","get_in_touch":"Tuntube Mu","desc":"Kuna da tambaya? Muna nan don taimakawa.","email":"Imel","phone":"Waya","address":"Adireshi","form_name":"Suna","form_name_ph":"Sunanka","form_email":"Imel","form_email_ph":"imel@naka.com","form_subject":"Jigo","form_subject_ph":"Yaya zamu taimaka?","form_message":"Saƙo","form_message_ph":"Saƙonka...","send":"Aika Saƙo","success":"Mun gode! Zamu tuntube ka nan ba da jimawa ba."},

    nav: { scanner: 'Abin Dubawa', templates: 'Falo', blog: 'Shafi', docs: 'Takardu', about: 'Game da', contact: 'Tuntuɓa', getStarted: 'Fara' },
    blog: { title: 'Kayan Aiki & Darussan', subtitle: 'Koyi yadda ake amfani da lambobin QR don kasuwancinku.', read_article: 'Karanta', back: '← Koma Kayan Aiki' },
    hero: { title: 'Lambobin QR na Kwararru a Daƙiƙa', subtitle: 'Ƙirƙiri kyawawan lambobin QR tare da tambari. 3 na farko kyauta ne 100% — ba rajista.', createBtn: 'Ƙirƙiri QR', scanBtn: 'Duba QR', preview: 'Dubawa' },
    features: { title: 'Ayyuka Masu Ƙarfi', subtitle: 'Duk abin da kuke buƙata don ƙirƙirar lambobin QR na ƙwararru', f1Title: 'Ire-iren QR 35+', f1Desc: 'Ƙirƙiri lambobin QR na URL, imel, WiFi, vCard, da sauransu', f2Title: 'Canje-canje na Musamman', f2Desc: 'Cikakken iko akan launuka da tsari', f3Title: 'Siffofi Daban-daban', f3Desc: 'Fitar a matsayin PNG, SVG, JPEG, PDF', f4Title: 'Dubawa Nan Take', f4Desc: 'Gani canje-canje nan take', f5Title: 'Don Waya', f5Desc: 'Yana aiki akan duk na\'urori', f6Title: 'Tsaro', f6Desc: 'Duk a cikin manhajarka - ba a ajiye bayanai' },
    types: { title: 'Ire-iren QR 35+', subtitle: 'Taimako ga duk irin QR' },
    why: { title: 'Me Yasa Za Ku Zaɓe Mu?', w1Title: 'Sirri 100%', w1Desc: 'Babu bayanan da ake aikawa zuwa ma\'ajiyarmu.', w2Title: 'Sauri', w2Desc: 'Ƙirƙiri lambobin QR nan take.', w3Title: 'Ba Rajista', w3Desc: 'Fara nan take ba tare da asusu ba.', w4Title: 'Cikakken Canje-canje', w4Desc: 'Sarrafa kowane sashe na QR ɗinku.', w5Title: 'Siffofi Daban-daban', w5Desc: 'Sauke a PNG, JPEG, SVG, PDF.', w6Title: 'Kwararru', w6Desc: 'Ƙirƙiri QR na firinta.' },
    faq: { title: 'Tambayoyin Da Ake Yawan Yi', subtitle: 'Nemo amsoshi game da injin QR ɗinmu', q1: 'Ana adana bayanai na?', a1: "A'a, ba a adana komai ba.", q2: 'Zan iya amfani da su don kasuwanci?', a2: 'Eh, tabbas. Ba sa ƙarewa.', q3: 'Kyauta ne gaba ɗaya?', a3: 'Guda 3 na farko kyauta ne. Bayan nan ₦1,000 ne kacal don amfani na dindindin.', q4: 'Ina buƙatar asusu?', a4: "A'a, imel kawai don rasiti.", q5: 'Zan iya gyara fasalin?', a5: 'Eh, launuka, tambari da sauransu.', q6: "Menene mafi girman girma?", a6: 'Har 1000x1000 pixels.' },
    cta: { title: 'Kun Shirya Don Ƙirƙira?', subtitle: 'Fara ƙirƙirar QR a daƙiƙa', btn: 'Fara Yanzu' },
    footer: { tagline: 'Ƙirƙirar QR na kwararru a sauƙaƙe.', product: 'Samfuri', generator: 'Injin Ƙirƙira', resources: 'Kayan Aiki', documentation: 'Takardu', legal: 'Dokoki', pricing: 'Farashi', privacy: 'Tsarin Sirri', terms: 'Sharuɗɗan Amfani', copyright: '© 2026 KennyKentola Digital QR Code Generator.' },
    generator: {
      title: 'Injin Ƙirƙirar QR', subtitle: 'Ƙirƙiri QR na kwararru', unlimited: 'Samun Dama mara iyaka', free_left: 'ƙirƙira kyauta da suka rage', free_left_single: 'ƙirƙira kyauta da ta rage',
      qr_type: 'Irin QR', content: 'Abun ciki', customization: 'Canje-canje', tab_colors: 'Launuka', tab_style: 'Tsari', tab_size: 'Girma', tab_logo: 'Tambari', fg_color: 'Launin gaba', bg_color: 'Launin baya',
      err_corr: 'Matakin Kuskure', err_l: 'Kadan (7%)', err_m: 'Tsaka-tsaki (15%)', err_q: 'Kashi ashirin da biyar (25%)', err_h: 'Babba (30%) - yafi kyau da tambari', margin: 'Gefen', modules: 'modules', size: 'Girma',
      dropzone: 'Jawo tambari anan, ko danna don zaɓa', dropzone_hint: 'Yana goyan bayan PNG, JPG, WEBP (Kada ya wuce 2MB)', or_url: 'Ko shigar da URL', logo_size: 'Girman tambari', remove_logo: 'Cire Tambari', generating: 'Ana ƙirƙira...',
      waiting: 'Ana jiran bayani don ƙirƙira', fill_in: 'Sanya bayani don ƙirƙira', limit_reached: 'An Kawo Ƙarshe', limit_desc: 'Biya ₦1,000 don buɗewa har abada.',
      unlock_btn: 'Buɗe Yanzu', unlock_unlimited: 'Buɗe Har Abada — Biya ₦1,000', copy: 'Kwafa', share: 'Raba', reset: 'Sake Komai', free_remaining_1: 'cikin 3 kyauta sun rage — biya ₦1,000 don amfani na dindindin', free_remaining_2: 'Kun gama na kyauta — biya ₦1,000 don buɗewa har abada'
    },
    scanner: {
      title: 'Injin Duba Lambar QR', subtitle: 'Duba da kyamararka ko ka loda hoto — sakamako yana fitowa nan take',
      live_cam: 'Injin Duba na Kyamara', cam_preview: 'Hoton kyamara zai fito anan', scanning: 'Ana dubawa…', stop_cam: 'Tsayar da Kyamara', start_cam: 'Fara Kyamara',
      upload_img: 'Loda Hoto', click_upload: 'Danna don loda hoto', formats: 'Yana goyan bayan PNG, JPG, WEBP', choose_img: 'Zaɓi Hoto',
      decoded: 'Sakamakon Dubawa', open_link: 'Bude hanyar ↗', copy_res: 'Kwafi Sakamako', clear: 'Share',
      private_title: 'Sirri 100%', private_desc: 'Duk dubawa yana faruwa a cikin manhajarka. Ba a tura kyamararka ko hotunanka zuwa wani guri. Don sakamako mai kyau, tabbatar QR ɗin ya fito radau kuma yana da haske.',
      toast_detected: 'An ga lambar QR!', toast_decoded: 'An karanta lambar QR dakyau!', toast_not_found: 'Ba a ga lambar QR ba. Da fatan za a gwada hoto mai haske.', toast_analyze_fail: 'An gaza nazarin hoto', toast_process_fail: 'An gaza sarrafa hoto', toast_copied: 'An kwafa', toast_copy_fail: 'An gaza kwafa',
      cam_error_perm: 'Ba a bada damar kyamara ba. Da fatan za a bada dama a saitunan manhajarka.', cam_error_acc: 'An gaza samun kyamara. Tabbatar kyamara tana aiki.'
    }
  },
  ig: {
    about: {"title":"Maka Ihe Nmepụta QR","subtitle":"Ebumnuche anyị bụ ime ka ịmepụta koodu QR dị mfe ma dị ngwa","mission":"Ebumnuche Anyị","m1":"Anyị kwenyere na onye ọ bụla kwesịrị inwe koodu QR. Anyị na-enye ụzọ n'efu ma dị nchebe.","m2":"Ma ị bụ onye nwe azụmahịa ma ọ bụ onye nrụpụta, ngwa anyị dị mfe iji.","values":"Uru Anyị","v1Title":"Onye Ọrụ Na Mbụ","v1Desc":"Anyị na-ebute onye ọrụ ụzọ.","v2Title":"Ọsọ","v2Desc":"Ọsọ dị ka amụma.","v3Title":"Nzuzo","v3Desc":"Ihe niile na-eme na nchọgharị gị. Anyị anaghị echekwa data gị.","v4Title":"Nnweta","v4Desc":"N'efu, enweghị ndebanye aha.","why":"Gịnị mere ị ga-eji họrọ anyị?","w1":"Ụdị QR 35+","w2":"Nhazi dị elu","w3":"Ụdị dị iche iche","w4":"Ịhụ ozugbo","w5":"100% n'efu","w6":"Nzuzo 100%"},
    faq_page: {"title":"Ajụjụ Ndị A Na-ajụkarị","subtitle":"Chọta azịza gbasara Ihe Nmepụta QR","q1":"Ọ bụ n'efu?","a1":"3 nke mbụ bụ n'efu. Mgbe ahụ ₦1,000 maka iji mgbe niile.","q2":"A chọrọ m akaụntụ?","a2":"Mba, ịchọghị akaụntụ.","q3":"E chekwara data m?","a3":"Mba, anyị anaghị echekwa data gị.","q4":"Kedu ụdị QR dị?","a4":"Anyị nwere ụdị 35+ gụnyere URL na WiFi.","q5":"Enwere m ike ịhazi ya?","a5":"Ee, ị nwere ike ịgbanwe agba na logo.","q6":"Kedu ụdị m ga-ebudata?","a6":"PNG, JPEG, SVG, na PDF.","q7":"Enwere m ike iji ya maka azụmahịa?","a7":"Ee, kpamkpam.","q8":"Otu esi enyocha QR?","a8":"Jiri igwefoto ekwentị gị ma ọ bụ Ihe Nyocha anyị.","q9":"Kedu ihe bụ mmezi njehie?","a9":"Ọ na-egosi otu koodu ahụ ga-esi arụ ọrụ ma ọ mebie obere.","q10":"Enwere m ike ịgbanwe QR?","a10":"Mba, ị ga-emepụta nke ọhụrụ."},
    pricing_page: {"title":"Ọnụ ahịa Dị Mfe","subtitle":"Nwalee n'efu, kwụọ otu ugboro.","free":"Nnwale N'efu","free_price":"₦0","free_sub":"Koodu QR 3 nke mbụ bụ n'efu","f1":"Ruo koodu 3","f2":"Ụdị QR 35+","f3":"Nbudata PNG na JPEG","f4":"Agba na ụdị","f5":"Tinye logo","start_free":"Bido Nnwale","premium":"Nnweta Oge Niile","premium_price":"₦1,000","premium_sub":"Ịkwụ ụgwọ otu oge","p1":"Koodu na-akparaghị ókè","p2":"Ụdị niile 35+","p3":"PNG, JPEG, SVG & PDF","p4":"Nhazi dị elu","p5":"Logo pụrụ iche","p6":"Enweghị ụgwọ kwa ọnwa","get_unlimited":"Nweta Oge Niile"},
    contact: {"title":"Kpọtụrụ Anyị","subtitle":"Anyị ga-achọ ịnụ olu gị","get_in_touch":"Kpo Anyị Pụ","desc":"Ị nwere ajụjụ? Anyị nọ ebe a iji nyere gị aka.","email":"Email","phone":"Ekwentị","address":"Adreesị","form_name":"Aha","form_name_ph":"Aha gị","form_email":"Email","form_email_ph":"email@gị.com","form_subject":"Isiokwu","form_subject_ph":"Olee otu anyị ga-esi nyere aka?","form_message":"Ozi","form_message_ph":"Ozi gị...","send":"Ziga Ozi","success":"Daalụ! Anyị ga-aza gị n'oge adịghị anya."},

    nav: { scanner: 'Ihe nyocha', templates: 'Ụdị', blog: 'Blọgụ', docs: 'Akwụkwọ', about: 'Maka', contact: 'Kpọtụrụ', getStarted: 'Bido' },
    blog: { title: 'Ihe Enyemaka & Ọzụzụ', subtitle: 'Mụta otu esi eji koodu QR maka azụmahịa gị.', read_article: 'Gụọ Akụkọ', back: '← Laghachi n\'Ihe Enyemaka' },
    hero: { title: 'Koodu QR ndị Ọkachamara na Nkejinta', subtitle: 'Mepụta koodu QR mara mma. 3 nke mbụ bụ n\'efu 100% — enweghị ndebanye aha.', createBtn: 'Mepụta QR', scanBtn: 'Nyochaa QR', preview: 'Hụ QR' },
    features: { title: 'Ihe Ndị Dị Ike', subtitle: 'Ihe niile ị chọrọ iji mepụta koodu QR ndị ọkachamara', f1Title: 'Ụdị QR 35+', f1Desc: 'Mepụta maka URL, email, WiFi, vCard na ndị ọzọ', f2Title: 'Nhazi dị elu', f2Desc: 'Njikwa zuru oke na agba na ụdị', f3Title: 'Ụdị Dị Iche Iche', f3Desc: 'Bupụta dị ka PNG, SVG, JPEG, PDF', f4Title: 'Ịhụ ozugbo', f4Desc: 'Hụ mgbanwe ozugbo', f5Title: 'Maka Ekwentị', f5Desc: 'Na-arụ ọrụ na ngwaọrụ niile', f6Title: 'Nchebe', f6Desc: 'Ihe niile dị na nchọgharị gị - enweghị data echekwara' },
    types: { title: 'Ụdị QR 35+', subtitle: 'Nkwado maka ụdị QR ọ bụla' },
    why: { title: 'Gịnị mere ị ga-eji họrọ anyị?', w1Title: '100% Nzuzo', w1Desc: 'Enweghị data ezigara na sava anyị.', w2Title: 'Ọsọ Ọsọ', w2Desc: 'Mepụta ozugbo.', w3Title: 'Enweghị Ndebanye Aha', w3Desc: 'Bido ozugbo.', w4Title: 'Enwere ike ịhazi', w4Desc: 'Jikwaa akụkụ niile.', w5Title: 'Ụdị Dị Iche Iche', w5Desc: 'Budata na PNG, JPEG, SVG, PDF.', w6Title: 'Ọkachamara', w6Desc: 'Mepụta maka obibi akwụkwọ.' },
    faq: { title: 'Ajụjụ Ndị A Na-ajụkarị', subtitle: 'Chọta azịza gbasara ihe njepụta anyị', q1: 'E chekwara data m?', a1: "Mba, echekwaghị ihe ọ bụla.", q2: 'Enwere m ike iji ha maka azụmahịa?', a2: 'Ee. Ha anaghị agwụ agwụ.', q3: 'Ọ bụ n\'efu?', a3: '3 nke mbụ bụ n\'efu. Mgbe ahụ ₦1,000 maka iji mgbe niile.', q4: 'A chọrọ m akaụntụ?', a4: "Mba, naanị email maka nnata.", q5: 'Enwere m ike ịhazi ya?', a5: 'Ee, agba, na akara gị.', q6: "Gịnị bụ kacha ibu?", a6: 'Ruo 1000x1000 pixels.' },
    cta: { title: 'Ị Jikere Ịmepụta?', subtitle: 'Bido ịmepụta na nkejinta', btn: 'Bido Ugbu A' },
    footer: { tagline: 'Ịmepụta koodu QR dị mfe.', product: 'Ngwaahịa', generator: 'Ihe Nmepụta', resources: 'Ihe Enyemaka', documentation: 'Akwụkwọ', legal: 'Iwu', pricing: 'Ọnụ ahịa', privacy: 'Iwu Nzuzo', terms: 'Usoro Ọrụ', copyright: '© 2026 KennyKentola Digital QR Code Generator.' },
    generator: {
      title: 'Ihe Nmepụta QR Code', subtitle: 'Mepụta koodu QR ozugbo', unlimited: 'Nnweta Na-akparaghị Ókè', free_left: 'n\'efu fọdụrụ', free_left_single: 'n\'efu fọdụrụ',
      qr_type: 'Ụdị QR', content: 'Ihe Dị N\'ime', customization: 'Nhazi', tab_colors: 'Agba', tab_style: 'Ụdị', tab_size: 'Ogo', tab_logo: 'Logo', fg_color: 'Agba Ihu', bg_color: 'Agba Azụ',
      err_corr: 'Mmezi Njehie', err_l: 'Dị ala (7%)', err_m: 'Nkezi (15%)', err_q: 'Nkeji iri abụọ na ise (25%)', err_h: 'Dị elu (30%) - kacha mma na logo', margin: 'Mpaghara', modules: 'modules', size: 'Ogo',
      dropzone: 'Dọrọ logo ebe a, ma ọ bụ pịa ịhọrọ', dropzone_hint: 'Na-akwado PNG, JPG, WEBP (Ruo 2MB)', or_url: 'Ma ọ bụ tinye URL', logo_size: 'Ogo logo', remove_logo: 'Wepụ Logo', generating: 'Na-emepụta...',
      waiting: 'Na-eche maka ozi', fill_in: 'Dejupụta ozi iji mepụta koodu QR gị', limit_reached: 'Eruola Oke', limit_desc: 'Kwụọ ₦1,000 iji nweta ike oge niile.',
      unlock_btn: 'Kpọghe Ugbu a', unlock_unlimited: 'Kpọghe Oge Niile — Kwụọ ₦1,000', copy: 'Deṅomie', share: 'Kekọrịta', reset: 'Tọgharịa Ihe Niile', free_remaining_1: 'nke 3 n\'efu fọdụrụ — kwụọ ₦1,000 maka iji mgbe niile', free_remaining_2: 'Ọ gwụla n\'efu — kwụọ ₦1,000 maka iji mgbe niile'
    },
    scanner: {
      title: 'Ihe Nyocha Koodu QR', subtitle: 'Jiri igwefoto gị nyochaa ma ọ bụ bulite foto — nsonaazụ na-apụta ozugbo',
      live_cam: 'Ihe Nyocha Igwefoto Ozugbo', cam_preview: 'Igwefoto ga-apụta ebe a', scanning: 'Na-enyocha…', stop_cam: 'Kwụsị Igwefoto', start_cam: 'Malite Igwefoto',
      upload_img: 'Bulite Foto', click_upload: 'Pịa iji bulite foto', formats: 'Na-akwado PNG, JPG, WEBP', choose_img: 'Họrọ Foto',
      decoded: 'Ihe Achọtara', open_link: 'Mepee njikọ ↗', copy_res: 'Deṅomie Nsonaazụ', clear: 'Kpochapụ',
      private_title: '100% Nyocha Nzuzo', private_desc: 'Nyocha niile na-eme n\'ime nchọgharị gị. A naghị ezipụ igwefoto ma ọ bụ foto gị na sava ọ bụla. Maka nsonaazụ kacha mma, hụ na koodu QR doro anya.',
      toast_detected: 'Ahụla koodu QR!', toast_decoded: 'A gụọla koodu QR nke ọma!', toast_not_found: 'Ahụghị koodu QR ọ bụla. Biko gbalịa foto doro anya.', toast_analyze_fail: 'Enweghị ike inyocha foto', toast_process_fail: 'Enweghị ike ịrụ ọrụ na foto', toast_copied: 'E depụtaghachiri ya', toast_copy_fail: 'Enweghị ike iṅomi',
      cam_error_perm: 'Ajụla ikike igwefoto. Biko nye ikike igwefoto na ntọala nchọgharị gị.', cam_error_acc: 'Enweghị ike ịnweta igwefoto. Biko hụ na ejikọtara igwefoto.'
    }
  }
};

export function t(lang: string, section: string, key: string): string {
  return translations[lang]?.[section]?.[key] ?? translations['en'][section]?.[key] ?? key;
}
