// Built-in i18n — zero external dependencies
// All translations stored here, managed via React context in i18nContext.tsx

export const translations: Record<string, Record<string, Record<string, string>>> = {
  en: {
    nav: { scanner: 'Scanner', templates: 'Templates', blog: 'Blog', docs: 'Docs', about: 'About', contact: 'Contact', getStarted: 'Get Started' },
    hero: { title: 'Professional QR Codes in Seconds', subtitle: 'Create beautiful, customizable QR codes with logo support. Your first 3 codes are 100% free — no registration required.', createBtn: 'Create QR Code', scanBtn: 'Scan QR Code', preview: 'QR Code Preview' },
    features: { title: 'Powerful Features', subtitle: 'Everything you need to create professional QR codes with advanced customization', f1Title: '35+ QR Types', f1Desc: 'Generate QR codes for URLs, emails, WiFi, vCard, payments, social media, and more', f2Title: 'Advanced Customization', f2Desc: 'Full control over colors, styles, logo placement, and frame designs', f3Title: 'Multiple Formats', f3Desc: 'Export as PNG, SVG, JPEG, PDF, or high-resolution for print', f4Title: 'Real-time Preview', f4Desc: 'See changes instantly as you customize your QR code', f5Title: 'Mobile Optimized', f5Desc: 'Works perfectly on all devices with responsive design', f6Title: 'Secure & Private', f6Desc: 'All processing happens in your browser - no data stored' },
    types: { title: '35+ QR Code Types', subtitle: 'Support for every QR code type you could need' },
    why: { title: 'Why Choose Us?', w1Title: '100% Private', w1Desc: 'All processing happens in your browser. No data is sent to our servers.', w2Title: 'Lightning Fast', w2Desc: 'Generate QR codes instantly with real-time preview updates.', w3Title: 'No Registration', w3Desc: 'Start generating QR codes immediately without creating an account.', w4Title: 'Fully Customizable', w4Desc: 'Control every aspect of your QR code design and appearance.', w5Title: 'Multiple Formats', w5Desc: 'Download in PNG, JPEG, SVG, PDF, or high-resolution formats.', w6Title: 'Professional Grade', w6Desc: 'Create print-ready QR codes for professional use.' },
    faq: { title: 'Frequently Asked Questions', subtitle: 'Find answers to common questions about our QR code generator', q1: 'Is my data stored anywhere?', a1: "No, all QR code generation happens entirely in your browser. We don't store or transmit any of your data to our servers. Your payment status is stored safely in your local browser storage.", q2: 'Can I use these QR codes commercially?', a2: 'Yes, absolutely. You can use QR codes generated here for any purpose - personal, commercial, or otherwise. They never expire.', q3: 'Is this completely free?', a3: 'Your first 3 QR code generations are 100% free. After that, we charge a tiny one-time fee of ₦1,000 for lifetime unlimited access to all features, including logo uploads. No monthly subscriptions.', q4: 'Do I need to create an account?', a4: 'No account needed! Even when paying the one-time ₦1,000 fee, you just enter your email for the receipt. Your access is tied to your browser instantly.', q5: 'Can I customize the appearance of QR codes?', a5: 'Yes, you can customize colors, sizes, error correction levels, margins, and upload your own logo to be centered on the QR code.', q6: "What's the maximum QR code size?", a6: 'You can generate QR codes up to 1000x1000 pixels. For print quality, we recommend downloading as PNG at the highest size setting.' },
    cta: { title: 'Ready to Create Your QR Code?', subtitle: 'Start generating professional QR codes in seconds', btn: 'Get Started Now' },
    footer: { tagline: 'Professional QR code generation made simple.', product: 'Product', generator: 'Generator', resources: 'Resources', documentation: 'Documentation', legal: 'Legal', pricing: 'Pricing', privacy: 'Privacy Policy', terms: 'Terms of Service', copyright: '© 2026 KennyKentola Digital QR Code Generator. All rights reserved.' },
    generator: {
      title: 'QR Code Generator', subtitle: 'Create professional QR codes instantly with advanced customization', unlimited: 'Unlimited Access', free_left: 'free generations left', free_left_single: 'free generation left',
      qr_type: 'QR Type', content: 'Content', customization: 'Customization', tab_colors: 'Colors', tab_style: 'Style', tab_size: 'Size', tab_logo: 'Logo', fg_color: 'Foreground Color', bg_color: 'Background Color',
      err_corr: 'Error Correction Level', err_l: 'Low (7%) — smaller QR', err_m: 'Medium (15%)', err_q: 'Quartile (25%)', err_h: 'High (30%) — best with logo', margin: 'Margin', modules: 'modules', size: 'Size',
      dropzone: 'Drag & drop your logo here, or click to select', dropzone_hint: 'Supports PNG, JPG, WEBP (Max 2MB)', upload_logo: 'Upload logo', logo_preview: 'Logo preview', logo_loaded: 'Logo loaded ✓', drop_logo: 'Drop your logo here', logo_formats: 'PNG, JPG, SVG supported', or_url: 'Or enter image URL', logo_size: 'Logo Size', remove_logo: 'Remove Logo', generating: 'Generating...',
      waiting: 'Waiting for input to generate QR code', fill_in: 'Fill in the content to generate your QR code', limit_reached: 'Limit Reached', limit_desc: 'Pay ₦1,000 to unlock this QR code and unlimited generations.',
      unlock_btn: 'Unlock Now', unlock_unlimited: 'Unlock Unlimited — Pay ₦1,000', copy: 'Copy', share: 'Share', reset: 'Reset All', free_remaining_1: 'of 3 free generations remaining — pay ₦1,000 for unlimited access', free_remaining_2: 'Free limit reached — pay ₦1,000 to unlock unlimited QR codes'
    }
  },
  es: {
    nav: { scanner: 'Escáner', templates: 'Plantillas', blog: 'Blog', docs: 'Documentación', about: 'Acerca de', contact: 'Contacto', getStarted: 'Empezar' },
    hero: { title: 'Códigos QR profesionales en segundos', subtitle: 'Cree hermosos códigos QR personalizables con soporte de logotipo. Sus primeros 3 códigos son 100% gratuitos, sin registro.', createBtn: 'Crear Código QR', scanBtn: 'Escanear Código QR', preview: 'Vista previa del Código QR' },
    features: { title: 'Funciones Potentes', subtitle: 'Todo lo que necesita para crear códigos QR profesionales con personalización avanzada', f1Title: '35+ Tipos de QR', f1Desc: 'Genere códigos QR para URLs, correos, WiFi, vCard, pagos, redes sociales y más', f2Title: 'Personalización Avanzada', f2Desc: 'Control total sobre colores, estilos, colocación del logotipo y diseños de marco', f3Title: 'Múltiples Formatos', f3Desc: 'Exporte como PNG, SVG, JPEG, PDF o alta resolución para imprimir', f4Title: 'Vista Previa en Tiempo Real', f4Desc: 'Vea los cambios al instante mientras personaliza su código QR', f5Title: 'Optimizado para Móviles', f5Desc: 'Funciona perfectamente en todos los dispositivos con diseño responsivo', f6Title: 'Seguro y Privado', f6Desc: 'Todo el procesamiento ocurre en su navegador, sin datos almacenados' },
    types: { title: '35+ Tipos de Código QR', subtitle: 'Soporte para cada tipo de código QR que pueda necesitar' },
    why: { title: '¿Por qué Elegirnos?', w1Title: '100% Privado', w1Desc: 'Todo el procesamiento ocurre en su navegador. No se envían datos a nuestros servidores.', w2Title: 'Rapidísimo', w2Desc: 'Genere códigos QR al instante con vista previa en tiempo real.', w3Title: 'Sin Registro', w3Desc: 'Comience a generar códigos QR inmediatamente sin crear una cuenta.', w4Title: 'Totalmente Personalizable', w4Desc: 'Controle cada aspecto del diseño y apariencia de su código QR.', w5Title: 'Múltiples Formatos', w5Desc: 'Descargue en PNG, JPEG, SVG, PDF o formatos de alta resolución.', w6Title: 'Calidad Profesional', w6Desc: 'Cree códigos QR listos para imprimir para uso profesional.' },
    faq: { title: 'Preguntas Frecuentes', subtitle: 'Encuentre respuestas a preguntas comunes sobre nuestro generador de códigos QR', q1: '¿Se almacenan mis datos en algún lugar?', a1: 'No, toda la generación de códigos QR ocurre completamente en su navegador. No almacenamos ni transmitimos ninguno de sus datos a nuestros servidores.', q2: '¿Puedo usar estos códigos QR comercialmente?', a2: 'Sí, absolutamente. Puede usar los códigos QR generados aquí para cualquier propósito: personal, comercial o de otro tipo. Nunca expiran.', q3: '¿Es esto completamente gratis?', a3: 'Sus primeras 3 generaciones de códigos QR son 100% gratuitas. Después, cobramos una pequeña tarifa única de ₦1,000 para acceso ilimitado de por vida.', q4: '¿Necesito crear una cuenta?', a4: '¡No se necesita cuenta! Incluso al pagar la tarifa única de ₦1,000, solo ingresa su correo electrónico para el recibo.', q5: '¿Puedo personalizar la apariencia de los códigos QR?', a5: 'Sí, puede personalizar colores, tamaños, niveles de corrección de errores, márgenes y subir su propio logotipo.', q6: '¿Cuál es el tamaño máximo del código QR?', a6: 'Puede generar códigos QR de hasta 1000x1000 píxeles. Para calidad de impresión, recomendamos descargar como PNG al tamaño más alto.' },
    cta: { title: '¿Listo para Crear su Código QR?', subtitle: 'Comience a generar códigos QR profesionales en segundos', btn: 'Comenzar Ahora' },
    footer: { tagline: 'Generación profesional de códigos QR simplificada.', product: 'Producto', generator: 'Generador', resources: 'Recursos', documentation: 'Documentación', legal: 'Legal', pricing: 'Precios', privacy: 'Política de Privacidad', terms: 'Términos de Servicio', copyright: '© 2026 KennyKentola Digital QR Code Generator. Todos los derechos reservados.' },
    generator: {
      title: 'Generador de Códigos QR', subtitle: 'Cree códigos QR profesionales al instante con personalización avanzada', unlimited: 'Acceso Ilimitado', free_left: 'generaciones gratuitas restantes', free_left_single: 'generación gratuita restante',
      qr_type: 'Tipo de QR', content: 'Contenido', customization: 'Personalización', tab_colors: 'Colores', tab_style: 'Estilo', tab_size: 'Tamaño', tab_logo: 'Logo', fg_color: 'Color de primer plano', bg_color: 'Color de fondo',
      err_corr: 'Nivel de corrección de errores', err_l: 'Bajo (7%) — QR más pequeño', err_m: 'Medio (15%)', err_q: 'Cuartil (25%)', err_h: 'Alto (30%) — mejor con logo', margin: 'Margen', modules: 'módulos', size: 'Tamaño',
      dropzone: 'Arrastre y suelte su logotipo aquí, o haga clic para seleccionar', dropzone_hint: 'Soporta PNG, JPG, WEBP (Max 2MB)', or_url: 'O ingrese la URL de la imagen', logo_size: 'Tamaño del logotipo', remove_logo: 'Eliminar logotipo', generating: 'Generando...',
      waiting: 'Esperando entrada para generar el código QR', fill_in: 'Complete el contenido para generar su código QR', limit_reached: 'Límite Alcanzado', limit_desc: 'Pague ₦1,000 para desbloquear este código QR y generaciones ilimitadas.',
      unlock_btn: 'Desbloquear Ahora', unlock_unlimited: 'Desbloquear Ilimitado — Pagar ₦1,000', copy: 'Copiar', share: 'Compartir', reset: 'Restablecer Todo', free_remaining_1: 'de 3 generaciones gratuitas restantes — pague ₦1,000 para acceso ilimitado', free_remaining_2: 'Límite gratuito alcanzado — pague ₦1,000 para desbloquear códigos QR ilimitados'
    }
  },
  fr: {
    nav: { scanner: 'Scanner', templates: 'Modèles', blog: 'Blog', docs: 'Documentation', about: 'À propos', contact: 'Contact', getStarted: 'Commencer' },
    hero: { title: 'Codes QR professionnels en quelques secondes', subtitle: 'Créez de superbes codes QR personnalisables avec prise en charge des logos. Vos 3 premiers codes sont 100 % gratuits, sans inscription.', createBtn: 'Créer un Code QR', scanBtn: 'Scanner un Code QR', preview: 'Aperçu du Code QR' },
    features: { title: 'Fonctionnalités Puissantes', subtitle: 'Tout ce dont vous avez besoin pour créer des codes QR professionnels avec une personnalisation avancée', f1Title: '35+ Types de QR', f1Desc: 'Générez des codes QR pour les URL, e-mails, WiFi, vCard, paiements, réseaux sociaux et plus', f2Title: 'Personnalisation Avancée', f2Desc: 'Contrôle total sur les couleurs, styles, placement du logo et designs de cadre', f3Title: 'Formats Multiples', f3Desc: 'Exportez en PNG, SVG, JPEG, PDF ou haute résolution pour impression', f4Title: 'Aperçu en Temps Réel', f4Desc: 'Voyez les changements instantanément pendant la personnalisation de votre code QR', f5Title: 'Optimisé pour Mobile', f5Desc: 'Fonctionne parfaitement sur tous les appareils avec un design responsive', f6Title: 'Sécurisé et Privé', f6Desc: 'Tout le traitement se fait dans votre navigateur, aucune donnée stockée' },
    types: { title: '35+ Types de Code QR', subtitle: 'Prise en charge de tous les types de codes QR dont vous avez besoin' },
    why: { title: 'Pourquoi Nous Choisir ?', w1Title: '100% Privé', w1Desc: 'Tout le traitement se fait dans votre navigateur. Aucune donnée envoyée à nos serveurs.', w2Title: 'Ultra Rapide', w2Desc: 'Générez des codes QR instantanément avec un aperçu en temps réel.', w3Title: 'Sans Inscription', w3Desc: 'Commencez à générer des codes QR immédiatement sans créer de compte.', w4Title: 'Entièrement Personnalisable', w4Desc: 'Contrôlez chaque aspect du design et de l\'apparence de votre code QR.', w5Title: 'Formats Multiples', w5Desc: 'Téléchargez en PNG, JPEG, SVG, PDF ou en haute résolution.', w6Title: 'Qualité Professionnelle', w6Desc: 'Créez des codes QR prêts à imprimer pour un usage professionnel.' },
    faq: { title: 'Questions Fréquemment Posées', subtitle: 'Trouvez des réponses aux questions courantes sur notre générateur de codes QR', q1: 'Mes données sont-elles stockées quelque part ?', a1: 'Non, toute la génération de codes QR se fait entièrement dans votre navigateur. Nous ne stockons ni ne transmettons aucune de vos données.', q2: 'Puis-je utiliser ces codes QR à des fins commerciales ?', a2: 'Oui, absolument. Vous pouvez utiliser les codes QR générés ici pour tout usage personnel, commercial ou autre. Ils n\'expirent jamais.', q3: 'Est-ce complètement gratuit ?', a3: 'Vos 3 premières générations de codes QR sont 100% gratuites. Ensuite, nous facturons un petit frais unique de ₦1,000 pour un accès illimité à vie.', q4: 'Dois-je créer un compte ?', a4: 'Aucun compte nécessaire ! Même en payant le frais unique de ₦1,000, vous entrez simplement votre e-mail pour le reçu.', q5: 'Puis-je personnaliser l\'apparence des codes QR ?', a5: 'Oui, vous pouvez personnaliser les couleurs, tailles, niveaux de correction d\'erreur, marges et télécharger votre propre logo.', q6: 'Quelle est la taille maximale du code QR ?', a6: 'Vous pouvez générer des codes QR jusqu\'à 1000x1000 pixels. Pour la qualité d\'impression, nous recommandons de télécharger en PNG à la taille maximale.' },
    cta: { title: 'Prêt à Créer Votre Code QR ?', subtitle: 'Commencez à générer des codes QR professionnels en quelques secondes', btn: 'Commencer Maintenant' },
    footer: { tagline: 'Génération professionnelle de codes QR simplifiée.', product: 'Produit', generator: 'Générateur', resources: 'Ressources', documentation: 'Documentation', legal: 'Juridique', pricing: 'Tarifs', privacy: 'Politique de Confidentialité', terms: 'Conditions d\'Utilisation', copyright: '© 2026 KennyKentola Digital QR Code Generator. Tous droits réservés.' },
    generator: {
      title: 'Générateur de Code QR', subtitle: 'Créez des codes QR professionnels instantanément avec une personnalisation avancée', unlimited: 'Accès Illimité', free_left: 'générations gratuites restantes', free_left_single: 'génération gratuite restante',
      qr_type: 'Type de QR', content: 'Contenu', customization: 'Personnalisation', tab_colors: 'Couleurs', tab_style: 'Style', tab_size: 'Taille', tab_logo: 'Logo', fg_color: 'Couleur de premier plan', bg_color: 'Couleur de fond',
      err_corr: 'Niveau de correction d\'erreur', err_l: 'Faible (7%) — QR plus petit', err_m: 'Moyen (15%)', err_q: 'Quartile (25%)', err_h: 'Élevé (30%) — meilleur avec logo', margin: 'Marge', modules: 'modules', size: 'Taille',
      dropzone: 'Glissez-déposez votre logo ici, ou cliquez pour sélectionner', dropzone_hint: 'Prend en charge PNG, JPG, WEBP (Max 2 Mo)', or_url: 'Ou entrez l\'URL de l\'image', logo_size: 'Taille du logo', remove_logo: 'Supprimer le logo', generating: 'Génération...',
      waiting: 'En attente d\'entrée pour générer le code QR', fill_in: 'Remplissez le contenu pour générer votre code QR', limit_reached: 'Limite Atteinte', limit_desc: 'Payez ₦1,000 pour débloquer ce code QR et des générations illimitées.',
      unlock_btn: 'Débloquer Maintenant', unlock_unlimited: 'Débloquer Illimité — Payer ₦1,000', copy: 'Copier', share: 'Partager', reset: 'Tout Réinitialiser', free_remaining_1: 'sur 3 générations gratuites restantes — payez ₦1,000 pour un accès illimité', free_remaining_2: 'Limite gratuite atteinte — payez ₦1,000 pour débloquer des codes QR illimités'
    }
  },
  yo: {
    nav: { scanner: 'Ẹrọ Ayẹwo', templates: 'Àwọn Àwòṣe', blog: 'Búlọ̀ọ̀gù', docs: 'Àwọn Ìwé', about: 'Nípa Wa', contact: 'Kàn sí wa', getStarted: 'Bẹ̀rẹ̀' },
    hero: { title: 'Koodu QR Alámọ̀dájú ní Ìṣẹ́jú Aáyá', subtitle: 'Ṣẹ̀dá àwọn koodu QR tó lẹ́wà, pẹ̀lú àtìlẹ́yìn àmì-iṣẹ́. Koodu 3 rẹ àkọ́kọ́ jẹ́ ọ̀fẹ́ 100% — kò sí ìforúkọsílẹ̀.', createBtn: 'Ṣẹ̀dá Koodu QR', scanBtn: 'Ṣàyẹ̀wò Koodu QR', preview: 'Àwòté Koodu QR' },
    features: { title: 'Àwọn Ẹ̀yà Pàtàkì', subtitle: 'Ohun gbogbo tí o nílò láti ṣẹ̀dá àwọn koodu QR alámọ̀dájú', f1Title: '35+ Oríṣi QR', f1Desc: 'Ṣẹ̀dá àwọn koodu QR fún URL, imeeli, WiFi, vCard, sísanwó, àti bẹ́ẹ̀ bẹ́ẹ̀ lọ', f2Title: 'Ìyípadà Àti Àtúnṣe', f2Desc: 'Ìṣàkóso ẹ̀kúnrẹ́rẹ́ lórí àwọ̀, ara, ìfilọ́lẹ̀ àmì, àti àpẹẹrẹ', f3Title: 'Oríṣiríṣi Fọ́mátì', f3Desc: 'Gbé e jáde gẹ́gẹ́ bí PNG, SVG, JPEG, PDF, tàbí gíga-fún-títẹ̀', f4Title: 'Àwòté Ìsinsìnyí', f4Desc: 'Rí àwọn àtúnṣe lẹ́sẹ̀kẹsẹ̀ bí o ṣe ń ṣe àtúnṣe koodu rẹ', f5Title: 'Dára fún Foonu', f5Desc: 'Ó ṣiṣẹ́ dáadáa lórí gbogbo ẹ̀rọ', f6Title: 'Ààbò àti Àṣírí', f6Desc: 'Gbogbo ìṣiṣẹ́ wáyé nínú burausa rẹ - kò sí dátà tí a tọ́jú' },
    types: { title: '35+ Oríṣi Koodu QR', subtitle: 'Àtìlẹ́yìn fún gbogbo oríṣi koodu QR tí o le nílò' },
    why: { title: 'Kí nìdí tí o fi yẹ kí o yàn wá?', w1Title: 'Àṣírí 100%', w1Desc: 'Gbogbo ìṣiṣẹ́ wáyé nínú burausa rẹ. A kò fi dátà kankan ránṣẹ́ sí sérfà wa.', w2Title: 'Yára bíi Mọ̀nàmọ́ná', w2Desc: 'Ṣẹ̀dá àwọn koodu QR lẹ́sẹ̀kẹsẹ̀ pẹ̀lú àwòté ìsinsìnyí.', w3Title: 'Kò sí Ìforúkọsílẹ̀', w3Desc: 'Bẹ̀rẹ̀ sí ṣẹ̀dá àwọn koodu QR lẹ́sẹ̀kẹsẹ̀ láìsí ìdásílẹ̀ àkọọnti.', w4Title: 'Àtúnṣe Ẹ̀kúnrẹ́rẹ́', w4Desc: 'Ṣàkóso gbogbo abala ìrísí àti wíwù koodu QR rẹ.', w5Title: 'Oríṣiríṣi Fọ́mátì', w5Desc: 'Gba wọlé gẹ́gẹ́ bí PNG, JPEG, SVG, PDF tàbí àwọn fọ́mátì gíga.', w6Title: 'Ipò Alámọ̀dájú', w6Desc: 'Ṣẹ̀dá àwọn koodu QR tó ṣetan fún títẹ̀.' },
    faq: { title: 'Àwọn Ìbéèrè Tí A Ń Bèèrè Lóòrèkóòrè', subtitle: 'Rí ìdáhùn sí àwọn ìbéèrè gbogbo nipa ẹ̀rọ QR wa', q1: 'Ṣé dátà mi wa ní ìpamọ́?', a1: "Bẹ́ẹ̀ kọ́, gbogbo rẹ̀ wáyé nínú burausa rẹ. A kò tọ́jú tàbí fi dátà rẹ ránṣẹ́.", q2: 'Ṣé mo le lo àwọn koodu QR wọ̀nyí fún iṣẹ́?', a2: 'Bẹ́ẹ̀ni, dájúdájú. O le lo wọn fún ohunkóhun, wọn kì í parí.', q3: 'Ṣé ọ̀fẹ́ ni pátápátá?', a3: 'Mẹ́ta àkọ́kọ́ jẹ́ ọ̀fẹ́. Lẹ́yìn náà, san ₦1,000 fún lílò tí kò lópin.', q4: 'Ṣé mo nílò àkọọnti?', a4: 'Rárá! Pẹ̀lú owo ₦1,000 náà, imeeli rẹ nìkan ni a nílò fún ìwé-ẹ̀rí.', q5: 'Ṣé mo le ṣe àtúnṣe ìrísí koodu QR?', a5: 'Bẹ́ẹ̀ni, o le yi àwọ̀, ìwọ̀n, àti fi àmì rẹ síi.', q6: "Kí ni ìwọ̀n tí ó pọ̀ jù fún koodu QR?", a6: 'O le ṣẹ̀dá rẹ̀ títí dé 1000x1000 pixels.' },
    cta: { title: 'Ṣé o ti ṣetan láti ṣẹ̀dá Koodu QR rẹ?', subtitle: 'Bẹ̀rẹ̀ sí ṣẹ̀dá àwọn koodu QR alámọ̀dájú ní ìṣẹ́jú aáyá', btn: 'Bẹ̀rẹ̀ Nísinsìnyí' },
    footer: { tagline: 'Ṣíṣẹ̀dá koodu QR alámọ̀dájú ni irọrun.', product: 'Ọjà', generator: 'Ẹrọ Ṣíṣẹ̀dá', resources: 'Àwọn Ohun-èlò', documentation: 'Àwọn Ìwé', legal: 'Òfin', pricing: 'Iye Owó', privacy: 'Ìlànà Àṣírí', terms: 'Àwọn Àdéhùn Iṣẹ́', copyright: '© 2026 KennyKentola Digital QR Code Generator. Gbogbo ẹ̀tọ́ wà ní ìpamọ́.' },
    generator: {
      title: 'Ẹrọ Ṣíṣẹ̀dá Koodu QR', subtitle: 'Ṣẹ̀dá àwọn koodu QR alámọ̀dájú lẹ́sẹ̀kẹsẹ̀', unlimited: 'Lílò Tí Kò Lópin', free_left: 'iṣẹ́ ọ̀fẹ́ tókù', free_left_single: 'iṣẹ́ ọ̀fẹ́ tókù',
      qr_type: 'Oríṣi QR', content: 'Àkóónú', customization: 'Àtúnṣe', tab_colors: 'Àwọ̀', tab_style: 'Ara', tab_size: 'Ìwọ̀n', tab_logo: 'Àmì-iṣẹ́', fg_color: 'Àwọ̀ Iwájú', bg_color: 'Àwọ̀ Ẹ̀yìn',
      err_corr: 'Ìpele Àtúnṣe Àṣìṣe', err_l: 'Kékeré (7%) — QR kéré', err_m: 'Aàrin (15%)', err_q: 'Ìdá Kẹrin (25%)', err_h: 'Gíga (30%) — dára pẹ̀lú àmì', margin: 'Ala', modules: 'modules', size: 'Ìwọ̀n',
      dropzone: 'Fa àmì rẹ sínú ibí, tàbí tẹ̀ láti mu', dropzone_hint: 'Ó ṣe atilẹyin PNG, JPG, WEBP (Max 2MB)', or_url: 'Tàbí kọ URL àwòrán', logo_size: 'Ìwọ̀n Àmì', remove_logo: 'Yọ Àmì', generating: 'Ó ń ṣẹ̀dá...',
      waiting: 'N dúró de àkóónú láti ṣẹ̀dá koodu QR', fill_in: 'Kọ àkóónú láti ṣẹ̀dá koodu QR rẹ', limit_reached: 'Ó ti dé òpin', limit_desc: 'San ₦1,000 láti ṣí koodu QR yí àti lílò tí kò lópin.',
      unlock_btn: 'Ṣí I Nísinsìnyí', unlock_unlimited: 'Ṣí Lílò Tí Kò Lópin — San ₦1,000', copy: 'Dàkọ', share: 'Pín', reset: 'Pa Gbogbo Rẹ Rẹ́', free_remaining_1: 'nínú 3 iṣẹ́ ọ̀fẹ́ tó kù — san ₦1,000 fún lílò tí kò lópin', free_remaining_2: 'Ó ti dé òpin ọ̀fẹ́ — san ₦1,000 láti ṣí lílò tí kò lópin'
    }
  },
  ha: {
    nav: { scanner: 'Abin Dubawa', templates: 'Falo', blog: 'Shafi', docs: 'Takardu', about: 'Game da', contact: 'Tuntuɓa', getStarted: 'Fara' },
    hero: { title: 'Lambobin QR na Kwararru a Daƙiƙa', subtitle: 'Ƙirƙiri kyawawan lambobin QR tare da tambari. 3 na farko kyauta ne 100% — ba rajista.', createBtn: 'Ƙirƙiri QR', scanBtn: 'Duba QR', preview: 'Dubawa' },
    features: { title: 'Ayyuka Masu Ƙarfi', subtitle: 'Duk abin da kuke buƙata don ƙirƙirar lambobin QR na ƙwararru', f1Title: 'Ire-iren QR 35+', f1Desc: 'Ƙirƙiri lambobin QR na URL, imel, WiFi, vCard, da sauransu', f2Title: 'Canje-canje na Musamman', f2Desc: 'Cikakken iko akan launuka da tsari', f3Title: 'Siffofi Daban-daban', f3Desc: 'Fitar a matsayin PNG, SVG, JPEG, PDF', f4Title: 'Dubawa Nan Take', f4Desc: 'Gani canje-canje nan take', f5Title: 'Don Waya', f5Desc: 'Yana aiki akan duk na\'urori', f6Title: 'Tsaro', f6Desc: 'Duk a cikin manhajarka - ba a ajiye bayanai' },
    types: { title: 'Ire-iren QR 35+', subtitle: 'Taimako ga duk irin QR' },
    why: { title: 'Me Yasa Za Ku Zaɓe Mu?', w1Title: 'Sirri 100%', w1Desc: 'Babu bayanan da ake aikawa zuwa ma\'ajiyarmu.', w2Title: 'Sauri', w2Desc: 'Ƙirƙiri lambobin QR nan take.', w3Title: 'Ba Rajista', w3Desc: 'Fara nan take ba tare da asusu ba.', w4Title: 'Cikakken Canje-canje', w4Desc: 'Sarrafa kowane sashe na QR ɗinku.', w5Title: 'Siffofi Daban-daban', w5Desc: 'Sauke a PNG, JPEG, SVG, PDF.', w6Title: 'Kwararru', w6Desc: 'Ƙirƙiri QR na firinta.' },
    faq: { title: 'Tambayoyin Da Ake Yawan Yi', subtitle: 'Nemo amsoshi game da injin QR ɗinmu', q1: 'Ana adana bayanai na?', a1: "A'a, ba a adana komai ba.", q2: 'Zan iya amfani da su don kasuwanci?', a2: 'Eh, tabbas. Ba sa ƙarewa.', q3: 'Kyauta ne gaba ɗaya?', a3: 'Guda 3 na farko kyauta ne. Bayan nan ₦1,000 ne kacal don amfani na dindindin.', q4: 'Ina buƙatar asusu?', a4: "A'a, imel kawai don rasiti.", q5: 'Zan iya gyara fasalin?', a5: 'Eh, launuka, tambari da sauransu.', q6: "Menene mafi girman girma?", a6: 'Har 1000x1000 pixels.' },
    cta: { title: 'Kun Shirya Don Ƙirƙira?', subtitle: 'Fara ƙirƙirar QR a daƙiƙa', btn: 'Fara Yanzu' },
    footer: { tagline: 'Ƙirƙirar QR na kwararru a sauƙaƙe.', product: 'Samfuri', generator: 'Injin Ƙirƙira', resources: 'Kayan Aiki', documentation: 'Takardu', legal: 'Dokoki', pricing: 'Farashi', privacy: 'Tsarin Sirri', terms: 'Sharuɗɗan Amfani', copyright: '© 2026 KennyKentola Digital QR Code Generator.' },
    generator: {
      title: 'Injin Ƙirƙirar QR', subtitle: 'Ƙirƙiri QR na kwararru', unlimited: 'Samun Dama mara iyaka', free_left: 'ƙirƙira kyauta da suka rage', free_left_single: 'ƙirƙira kyauta da ta rage',
      qr_type: 'Irin QR', content: 'Abun ciki', customization: 'Canje-canje', tab_colors: 'Launuka', tab_style: 'Tsari', tab_size: 'Girma', tab_logo: 'Tambari', fg_color: 'Launin gaba', bg_color: 'Launin baya',
      err_corr: 'Matakin Kuskure', err_l: 'Kadan (7%)', err_m: 'Tsaka-tsaki (15%)', err_q: 'Kashi ashirin da biyar (25%)', err_h: 'Babba (30%) - yafi kyau da tambari', margin: 'Gefen', modules: 'modules', size: 'Girma',
      dropzone: 'Jawo tambari anan, ko danna don zaɓa', dropzone_hint: 'Yana goyan bayan PNG, JPG, WEBP (Kada ya wuce 2MB)', or_url: 'Ko shigar da URL', logo_size: 'Girman tambari', remove_logo: 'Cire Tambari', generating: 'Ana ƙirƙira...',
      waiting: 'Ana jiran bayani don ƙirƙira', fill_in: 'Sanya bayani don ƙirƙira', limit_reached: 'An Kawo Ƙarshe', limit_desc: 'Biya ₦1,000 don buɗewa har abada.',
      unlock_btn: 'Buɗe Yanzu', unlock_unlimited: 'Buɗe Har Abada — Biya ₦1,000', copy: 'Kwafa', share: 'Raba', reset: 'Sake Komai', free_remaining_1: 'cikin 3 kyauta sun rage — biya ₦1,000 don amfani na dindindin', free_remaining_2: 'Kun gama na kyauta — biya ₦1,000 don buɗewa har abada'
    }
  },
  ig: {
    nav: { scanner: 'Ihe nyocha', templates: 'Ụdị', blog: 'Blọgụ', docs: 'Akwụkwọ', about: 'Maka', contact: 'Kpọtụrụ', getStarted: 'Bido' },
    hero: { title: 'Koodu QR ndị Ọkachamara na Nkejinta', subtitle: 'Mepụta koodu QR mara mma. 3 nke mbụ bụ n\'efu 100% — enweghị ndebanye aha.', createBtn: 'Mepụta QR', scanBtn: 'Nyochaa QR', preview: 'Hụ QR' },
    features: { title: 'Ihe Ndị Dị Ike', subtitle: 'Ihe niile ị chọrọ iji mepụta koodu QR ndị ọkachamara', f1Title: 'Ụdị QR 35+', f1Desc: 'Mepụta maka URL, email, WiFi, vCard na ndị ọzọ', f2Title: 'Nhazi dị elu', f2Desc: 'Njikwa zuru oke na agba na ụdị', f3Title: 'Ụdị Dị Iche Iche', f3Desc: 'Bupụta dị ka PNG, SVG, JPEG, PDF', f4Title: 'Ịhụ ozugbo', f4Desc: 'Hụ mgbanwe ozugbo', f5Title: 'Maka Ekwentị', f5Desc: 'Na-arụ ọrụ na ngwaọrụ niile', f6Title: 'Nchebe', f6Desc: 'Ihe niile dị na nchọgharị gị - enweghị data echekwara' },
    types: { title: 'Ụdị QR 35+', subtitle: 'Nkwado maka ụdị QR ọ bụla' },
    why: { title: 'Gịnị mere ị ga-eji họrọ anyị?', w1Title: '100% Nzuzo', w1Desc: 'Enweghị data ezigara na sava anyị.', w2Title: 'Ọsọ Ọsọ', w2Desc: 'Mepụta ozugbo.', w3Title: 'Enweghị Ndebanye Aha', w3Desc: 'Bido ozugbo.', w4Title: 'Enwere ike ịhazi', w4Desc: 'Jikwaa akụkụ niile.', w5Title: 'Ụdị Dị Iche Iche', w5Desc: 'Budata na PNG, JPEG, SVG, PDF.', w6Title: 'Ọkachamara', w6Desc: 'Mepụta maka obibi akwụkwọ.' },
    faq: { title: 'Ajụjụ Ndị A Na-ajụkarị', subtitle: 'Chọta azịza gbasara ihe njepụta anyị', q1: 'E chekwara data m?', a1: "Mba, echekwaghị ihe ọ bụla.", q2: 'Enwere m ike iji ha maka azụmahịa?', a2: 'Ee. Ha anaghị agwụ agwụ.', q3: 'Ọ bụ n\'efu?', a3: '3 nke mbụ bụ n\'efu. Mgbe ahụ ₦1,000 maka iji mgbe niile.', q4: 'A chọrọ m akaụntụ?', a4: "Mba, naanị email maka nnata.", q5: 'Enwere m ike ịhazi ya?', a5: 'Ee, agba, na akara gị.', q6: "Gịnị bụ kacha ibu?", a6: 'Ruo 1000x1000 pixels.' },
    cta: { title: 'Ị Jikere Ịmepụta?', subtitle: 'Bido ịmepụta na nkejinta', btn: 'Bido Ugbu A' },
    footer: { tagline: 'Ịmepụta koodu QR dị mfe.', product: 'Ngwaahịa', generator: 'Ihe Nmepụta', resources: 'Ihe Enyemaka', documentation: 'Akwụkwọ', legal: 'Iwu', pricing: 'Ọnụ ahịa', privacy: 'Iwu Nzuzo', terms: 'Usoro Ọrụ', copyright: '© 2026 KennyKentola Digital QR Code Generator.' },
    generator: {
      title: 'Ihe Nmepụta QR Code', subtitle: 'Mepụta koodu QR ozugbo', unlimited: 'Nnweta Na-akparaghị Ókè', free_left: 'n\'efu fọdụrụ', free_left_single: 'n\'efu fọdụrụ',
      qr_type: 'Ụdị QR', content: 'Ihe Dị N\'ime', customization: 'Nhazi', tab_colors: 'Agba', tab_style: 'Ụdị', tab_size: 'Ogo', tab_logo: 'Logo', fg_color: 'Agba Ihu', bg_color: 'Agba Azụ',
      err_corr: 'Mmezi Njehie', err_l: 'Dị ala (7%)', err_m: 'Nkezi (15%)', err_q: 'Nkeji iri abụọ na ise (25%)', err_h: 'Dị elu (30%) - kacha mma na logo', margin: 'Mpaghara', modules: 'modules', size: 'Ogo',
      dropzone: 'Dọrọ logo ebe a, ma ọ bụ pịa ịhọrọ', dropzone_hint: 'Na-akwado PNG, JPG, WEBP (Ruo 2MB)', or_url: 'Ma ọ bụ tinye URL', logo_size: 'Ogo logo', remove_logo: 'Wepụ Logo', generating: 'Na-emepụta...',
      waiting: 'Na-eche maka ozi', fill_in: 'Dejupụta ozi iji mepụta koodu QR gị', limit_reached: 'Eruola Oke', limit_desc: 'Kwụọ ₦1,000 iji nweta ike oge niile.',
      unlock_btn: 'Kpọghe Ugbu a', unlock_unlimited: 'Kpọghe Oge Niile — Kwụọ ₦1,000', copy: 'Deṅomie', share: 'Kekọrịta', reset: 'Tọgharịa Ihe Niile', free_remaining_1: 'nke 3 n\'efu fọdụrụ — kwụọ ₦1,000 maka iji mgbe niile', free_remaining_2: 'Ọ gwụla n\'efu — kwụọ ₦1,000 maka iji mgbe niile'
    }
  }
};

export function t(lang: string, section: string, key: string): string {
  return translations[lang]?.[section]?.[key] ?? translations['en'][section]?.[key] ?? key;
}
